// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armpolicyinsights

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
)

// ClientFactory is a client factory used to create any client in this module.
// Don't use this type directly, use NewClientFactory instead.
type ClientFactory struct {
	internal *arm.Client
}

// NewClientFactory creates a new instance of ClientFactory with the specified values.
// The parameter values will be propagated to any client created from this factory.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - pass nil to accept the default values.
func NewClientFactory(credential azcore.TokenCredential, options *arm.ClientOptions) (*ClientFactory, error) {
	internal, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	return &ClientFactory{
		internal: internal,
	}, nil
}

// NewAttestationsClient creates a new instance of AttestationsClient.
func (c *ClientFactory) NewAttestationsClient(subscriptionID string) *AttestationsClient {
	return &AttestationsClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}

// NewComponentPolicyStatesClient creates a new instance of ComponentPolicyStatesClient.
func (c *ClientFactory) NewComponentPolicyStatesClient(subscriptionID string) *ComponentPolicyStatesClient {
	return &ComponentPolicyStatesClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}

// NewOperationsClient creates a new instance of OperationsClient.
func (c *ClientFactory) NewOperationsClient() *OperationsClient {
	return &OperationsClient{
		internal: c.internal,
	}
}

// NewPolicyEventsClient creates a new instance of PolicyEventsClient.
func (c *ClientFactory) NewPolicyEventsClient(subscriptionID string) *PolicyEventsClient {
	return &PolicyEventsClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}

// NewPolicyMetadataClient creates a new instance of PolicyMetadataClient.
func (c *ClientFactory) NewPolicyMetadataClient() *PolicyMetadataClient {
	return &PolicyMetadataClient{
		internal: c.internal,
	}
}

// NewPolicyRestrictionsClient creates a new instance of PolicyRestrictionsClient.
func (c *ClientFactory) NewPolicyRestrictionsClient(subscriptionID string) *PolicyRestrictionsClient {
	return &PolicyRestrictionsClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}

// NewPolicyStatesClient creates a new instance of PolicyStatesClient.
func (c *ClientFactory) NewPolicyStatesClient(subscriptionID string) *PolicyStatesClient {
	return &PolicyStatesClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}

// NewPolicyTrackedResourcesClient creates a new instance of PolicyTrackedResourcesClient.
func (c *ClientFactory) NewPolicyTrackedResourcesClient(subscriptionID string) *PolicyTrackedResourcesClient {
	return &PolicyTrackedResourcesClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}

// NewRemediationsClient creates a new instance of RemediationsClient.
func (c *ClientFactory) NewRemediationsClient(subscriptionID string) *RemediationsClient {
	return &RemediationsClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}
