// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armpolicyinsights

// AttestationsClientBeginCreateOrUpdateAtResourceGroupOptions contains the optional parameters for the AttestationsClient.BeginCreateOrUpdateAtResourceGroup
// method.
type AttestationsClientBeginCreateOrUpdateAtResourceGroupOptions struct {
	// Resumes the long-running operation from the provided token.
	ResumeToken string
}

// AttestationsClientBeginCreateOrUpdateAtResourceOptions contains the optional parameters for the AttestationsClient.BeginCreateOrUpdateAtResource
// method.
type AttestationsClientBeginCreateOrUpdateAtResourceOptions struct {
	// Resumes the long-running operation from the provided token.
	ResumeToken string
}

// AttestationsClientBeginCreateOrUpdateAtSubscriptionOptions contains the optional parameters for the AttestationsClient.BeginCreateOrUpdateAtSubscription
// method.
type AttestationsClientBeginCreateOrUpdateAtSubscriptionOptions struct {
	// Resumes the long-running operation from the provided token.
	ResumeToken string
}

// AttestationsClientDeleteAtResourceGroupOptions contains the optional parameters for the AttestationsClient.DeleteAtResourceGroup
// method.
type AttestationsClientDeleteAtResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// AttestationsClientDeleteAtResourceOptions contains the optional parameters for the AttestationsClient.DeleteAtResource
// method.
type AttestationsClientDeleteAtResourceOptions struct {
	// placeholder for future optional parameters
}

// AttestationsClientDeleteAtSubscriptionOptions contains the optional parameters for the AttestationsClient.DeleteAtSubscription
// method.
type AttestationsClientDeleteAtSubscriptionOptions struct {
	// placeholder for future optional parameters
}

// AttestationsClientGetAtResourceGroupOptions contains the optional parameters for the AttestationsClient.GetAtResourceGroup
// method.
type AttestationsClientGetAtResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// AttestationsClientGetAtResourceOptions contains the optional parameters for the AttestationsClient.GetAtResource method.
type AttestationsClientGetAtResourceOptions struct {
	// placeholder for future optional parameters
}

// AttestationsClientGetAtSubscriptionOptions contains the optional parameters for the AttestationsClient.GetAtSubscription
// method.
type AttestationsClientGetAtSubscriptionOptions struct {
	// placeholder for future optional parameters
}

// OperationsClientListOptions contains the optional parameters for the OperationsClient.List method.
type OperationsClientListOptions struct {
	// placeholder for future optional parameters
}

// PolicyMetadataClientGetResourceOptions contains the optional parameters for the PolicyMetadataClient.GetResource method.
type PolicyMetadataClientGetResourceOptions struct {
	// placeholder for future optional parameters
}

// PolicyRestrictionsClientCheckAtManagementGroupScopeOptions contains the optional parameters for the PolicyRestrictionsClient.CheckAtManagementGroupScope
// method.
type PolicyRestrictionsClientCheckAtManagementGroupScopeOptions struct {
	// placeholder for future optional parameters
}

// PolicyRestrictionsClientCheckAtResourceGroupScopeOptions contains the optional parameters for the PolicyRestrictionsClient.CheckAtResourceGroupScope
// method.
type PolicyRestrictionsClientCheckAtResourceGroupScopeOptions struct {
	// placeholder for future optional parameters
}

// PolicyRestrictionsClientCheckAtSubscriptionScopeOptions contains the optional parameters for the PolicyRestrictionsClient.CheckAtSubscriptionScope
// method.
type PolicyRestrictionsClientCheckAtSubscriptionScopeOptions struct {
	// placeholder for future optional parameters
}

// PolicyStatesClientBeginTriggerResourceGroupEvaluationOptions contains the optional parameters for the PolicyStatesClient.BeginTriggerResourceGroupEvaluation
// method.
type PolicyStatesClientBeginTriggerResourceGroupEvaluationOptions struct {
	// Resumes the long-running operation from the provided token.
	ResumeToken string
}

// PolicyStatesClientBeginTriggerSubscriptionEvaluationOptions contains the optional parameters for the PolicyStatesClient.BeginTriggerSubscriptionEvaluation
// method.
type PolicyStatesClientBeginTriggerSubscriptionEvaluationOptions struct {
	// Resumes the long-running operation from the provided token.
	ResumeToken string
}

// RemediationsClientCancelAtManagementGroupOptions contains the optional parameters for the RemediationsClient.CancelAtManagementGroup
// method.
type RemediationsClientCancelAtManagementGroupOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientCancelAtResourceGroupOptions contains the optional parameters for the RemediationsClient.CancelAtResourceGroup
// method.
type RemediationsClientCancelAtResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientCancelAtResourceOptions contains the optional parameters for the RemediationsClient.CancelAtResource
// method.
type RemediationsClientCancelAtResourceOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientCancelAtSubscriptionOptions contains the optional parameters for the RemediationsClient.CancelAtSubscription
// method.
type RemediationsClientCancelAtSubscriptionOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientCreateOrUpdateAtManagementGroupOptions contains the optional parameters for the RemediationsClient.CreateOrUpdateAtManagementGroup
// method.
type RemediationsClientCreateOrUpdateAtManagementGroupOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientCreateOrUpdateAtResourceGroupOptions contains the optional parameters for the RemediationsClient.CreateOrUpdateAtResourceGroup
// method.
type RemediationsClientCreateOrUpdateAtResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientCreateOrUpdateAtResourceOptions contains the optional parameters for the RemediationsClient.CreateOrUpdateAtResource
// method.
type RemediationsClientCreateOrUpdateAtResourceOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientCreateOrUpdateAtSubscriptionOptions contains the optional parameters for the RemediationsClient.CreateOrUpdateAtSubscription
// method.
type RemediationsClientCreateOrUpdateAtSubscriptionOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientDeleteAtManagementGroupOptions contains the optional parameters for the RemediationsClient.DeleteAtManagementGroup
// method.
type RemediationsClientDeleteAtManagementGroupOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientDeleteAtResourceGroupOptions contains the optional parameters for the RemediationsClient.DeleteAtResourceGroup
// method.
type RemediationsClientDeleteAtResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientDeleteAtResourceOptions contains the optional parameters for the RemediationsClient.DeleteAtResource
// method.
type RemediationsClientDeleteAtResourceOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientDeleteAtSubscriptionOptions contains the optional parameters for the RemediationsClient.DeleteAtSubscription
// method.
type RemediationsClientDeleteAtSubscriptionOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientGetAtManagementGroupOptions contains the optional parameters for the RemediationsClient.GetAtManagementGroup
// method.
type RemediationsClientGetAtManagementGroupOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientGetAtResourceGroupOptions contains the optional parameters for the RemediationsClient.GetAtResourceGroup
// method.
type RemediationsClientGetAtResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientGetAtResourceOptions contains the optional parameters for the RemediationsClient.GetAtResource method.
type RemediationsClientGetAtResourceOptions struct {
	// placeholder for future optional parameters
}

// RemediationsClientGetAtSubscriptionOptions contains the optional parameters for the RemediationsClient.GetAtSubscription
// method.
type RemediationsClientGetAtSubscriptionOptions struct {
	// placeholder for future optional parameters
}
