// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armpolicyinsights

// AttestationsClientCreateOrUpdateAtResourceGroupResponse contains the response from method AttestationsClient.BeginCreateOrUpdateAtResourceGroup.
type AttestationsClientCreateOrUpdateAtResourceGroupResponse struct {
	// An attestation resource.
	Attestation
}

// AttestationsClientCreateOrUpdateAtResourceResponse contains the response from method AttestationsClient.BeginCreateOrUpdateAtResource.
type AttestationsClientCreateOrUpdateAtResourceResponse struct {
	// An attestation resource.
	Attestation
}

// AttestationsClientCreateOrUpdateAtSubscriptionResponse contains the response from method AttestationsClient.BeginCreateOrUpdateAtSubscription.
type AttestationsClientCreateOrUpdateAtSubscriptionResponse struct {
	// An attestation resource.
	Attestation
}

// AttestationsClientDeleteAtResourceGroupResponse contains the response from method AttestationsClient.DeleteAtResourceGroup.
type AttestationsClientDeleteAtResourceGroupResponse struct {
	// placeholder for future response values
}

// AttestationsClientDeleteAtResourceResponse contains the response from method AttestationsClient.DeleteAtResource.
type AttestationsClientDeleteAtResourceResponse struct {
	// placeholder for future response values
}

// AttestationsClientDeleteAtSubscriptionResponse contains the response from method AttestationsClient.DeleteAtSubscription.
type AttestationsClientDeleteAtSubscriptionResponse struct {
	// placeholder for future response values
}

// AttestationsClientGetAtResourceGroupResponse contains the response from method AttestationsClient.GetAtResourceGroup.
type AttestationsClientGetAtResourceGroupResponse struct {
	// An attestation resource.
	Attestation
}

// AttestationsClientGetAtResourceResponse contains the response from method AttestationsClient.GetAtResource.
type AttestationsClientGetAtResourceResponse struct {
	// An attestation resource.
	Attestation
}

// AttestationsClientGetAtSubscriptionResponse contains the response from method AttestationsClient.GetAtSubscription.
type AttestationsClientGetAtSubscriptionResponse struct {
	// An attestation resource.
	Attestation
}

// OperationsClientListResponse contains the response from method OperationsClient.List.
type OperationsClientListResponse struct {
	// List of available operations.
	OperationsListResults
}

// PolicyMetadataClientGetResourceResponse contains the response from method PolicyMetadataClient.GetResource.
type PolicyMetadataClientGetResourceResponse struct {
	// Policy metadata resource definition.
	PolicyMetadata
}

// PolicyRestrictionsClientCheckAtManagementGroupScopeResponse contains the response from method PolicyRestrictionsClient.CheckAtManagementGroupScope.
type PolicyRestrictionsClientCheckAtManagementGroupScopeResponse struct {
	// The result of a check policy restrictions evaluation on a resource.
	CheckRestrictionsResult
}

// PolicyRestrictionsClientCheckAtResourceGroupScopeResponse contains the response from method PolicyRestrictionsClient.CheckAtResourceGroupScope.
type PolicyRestrictionsClientCheckAtResourceGroupScopeResponse struct {
	// The result of a check policy restrictions evaluation on a resource.
	CheckRestrictionsResult
}

// PolicyRestrictionsClientCheckAtSubscriptionScopeResponse contains the response from method PolicyRestrictionsClient.CheckAtSubscriptionScope.
type PolicyRestrictionsClientCheckAtSubscriptionScopeResponse struct {
	// The result of a check policy restrictions evaluation on a resource.
	CheckRestrictionsResult
}

// PolicyStatesClientTriggerResourceGroupEvaluationResponse contains the response from method PolicyStatesClient.BeginTriggerResourceGroupEvaluation.
type PolicyStatesClientTriggerResourceGroupEvaluationResponse struct {
	// placeholder for future response values
}

// PolicyStatesClientTriggerSubscriptionEvaluationResponse contains the response from method PolicyStatesClient.BeginTriggerSubscriptionEvaluation.
type PolicyStatesClientTriggerSubscriptionEvaluationResponse struct {
	// placeholder for future response values
}

// RemediationsClientCancelAtManagementGroupResponse contains the response from method RemediationsClient.CancelAtManagementGroup.
type RemediationsClientCancelAtManagementGroupResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientCancelAtResourceGroupResponse contains the response from method RemediationsClient.CancelAtResourceGroup.
type RemediationsClientCancelAtResourceGroupResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientCancelAtResourceResponse contains the response from method RemediationsClient.CancelAtResource.
type RemediationsClientCancelAtResourceResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientCancelAtSubscriptionResponse contains the response from method RemediationsClient.CancelAtSubscription.
type RemediationsClientCancelAtSubscriptionResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientCreateOrUpdateAtManagementGroupResponse contains the response from method RemediationsClient.CreateOrUpdateAtManagementGroup.
type RemediationsClientCreateOrUpdateAtManagementGroupResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientCreateOrUpdateAtResourceGroupResponse contains the response from method RemediationsClient.CreateOrUpdateAtResourceGroup.
type RemediationsClientCreateOrUpdateAtResourceGroupResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientCreateOrUpdateAtResourceResponse contains the response from method RemediationsClient.CreateOrUpdateAtResource.
type RemediationsClientCreateOrUpdateAtResourceResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientCreateOrUpdateAtSubscriptionResponse contains the response from method RemediationsClient.CreateOrUpdateAtSubscription.
type RemediationsClientCreateOrUpdateAtSubscriptionResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientDeleteAtManagementGroupResponse contains the response from method RemediationsClient.DeleteAtManagementGroup.
type RemediationsClientDeleteAtManagementGroupResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientDeleteAtResourceGroupResponse contains the response from method RemediationsClient.DeleteAtResourceGroup.
type RemediationsClientDeleteAtResourceGroupResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientDeleteAtResourceResponse contains the response from method RemediationsClient.DeleteAtResource.
type RemediationsClientDeleteAtResourceResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientDeleteAtSubscriptionResponse contains the response from method RemediationsClient.DeleteAtSubscription.
type RemediationsClientDeleteAtSubscriptionResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientGetAtManagementGroupResponse contains the response from method RemediationsClient.GetAtManagementGroup.
type RemediationsClientGetAtManagementGroupResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientGetAtResourceGroupResponse contains the response from method RemediationsClient.GetAtResourceGroup.
type RemediationsClientGetAtResourceGroupResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientGetAtResourceResponse contains the response from method RemediationsClient.GetAtResource.
type RemediationsClientGetAtResourceResponse struct {
	// The remediation definition.
	Remediation
}

// RemediationsClientGetAtSubscriptionResponse contains the response from method RemediationsClient.GetAtSubscription.
type RemediationsClientGetAtSubscriptionResponse struct {
	// The remediation definition.
	Remediation
}
