// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/hybridcompute/armhybridcompute/v2"
	"net/http"
	"net/url"
	"regexp"
	"slices"
)

// AgentVersionServer is a fake server for instances of the armhybridcompute.AgentVersionClient type.
type AgentVersionServer struct {
	// Get is the fake for method AgentVersionClient.Get
	// HTTP status codes to indicate success: http.StatusOK
	Get func(ctx context.Context, osType string, version string, options *armhybridcompute.AgentVersionClientGetOptions) (resp azfake.Responder[armhybridcompute.AgentVersionClientGetResponse], errResp azfake.ErrorResponder)

	// NewListPager is the fake for method AgentVersionClient.NewListPager
	// HTTP status codes to indicate success: http.StatusOK
	NewListPager func(osType string, options *armhybridcompute.AgentVersionClientListOptions) (resp azfake.PagerResponder[armhybridcompute.AgentVersionClientListResponse])
}

// NewAgentVersionServerTransport creates a new instance of AgentVersionServerTransport with the provided implementation.
// The returned AgentVersionServerTransport instance is connected to an instance of armhybridcompute.AgentVersionClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewAgentVersionServerTransport(srv *AgentVersionServer) *AgentVersionServerTransport {
	return &AgentVersionServerTransport{
		srv:          srv,
		newListPager: newTracker[azfake.PagerResponder[armhybridcompute.AgentVersionClientListResponse]](),
	}
}

// AgentVersionServerTransport connects instances of armhybridcompute.AgentVersionClient to instances of AgentVersionServer.
// Don't use this type directly, use NewAgentVersionServerTransport instead.
type AgentVersionServerTransport struct {
	srv          *AgentVersionServer
	newListPager *tracker[azfake.PagerResponder[armhybridcompute.AgentVersionClientListResponse]]
}

// Do implements the policy.Transporter interface for AgentVersionServerTransport.
func (a *AgentVersionServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return a.dispatchToMethodFake(req, method)
}

func (a *AgentVersionServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if agentVersionServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = agentVersionServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "AgentVersionClient.Get":
				res.resp, res.err = a.dispatchGet(req)
			case "AgentVersionClient.NewListPager":
				res.resp, res.err = a.dispatchNewListPager(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (a *AgentVersionServerTransport) dispatchGet(req *http.Request) (*http.Response, error) {
	if a.srv.Get == nil {
		return nil, &nonRetriableError{errors.New("fake for method Get not implemented")}
	}
	const regexStr = `/providers/Microsoft\.HybridCompute/osType/(?P<osType>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/agentVersions/(?P<version>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 3 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	osTypeParam, err := url.PathUnescape(matches[regex.SubexpIndex("osType")])
	if err != nil {
		return nil, err
	}
	versionParam, err := url.PathUnescape(matches[regex.SubexpIndex("version")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := a.srv.Get(req.Context(), osTypeParam, versionParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).AgentVersion, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (a *AgentVersionServerTransport) dispatchNewListPager(req *http.Request) (*http.Response, error) {
	if a.srv.NewListPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewListPager not implemented")}
	}
	newListPager := a.newListPager.get(req)
	if newListPager == nil {
		const regexStr = `/providers/Microsoft\.HybridCompute/osType/(?P<osType>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/agentVersions`
		regex := regexp.MustCompile(regexStr)
		matches := regex.FindStringSubmatch(req.URL.EscapedPath())
		if len(matches) < 2 {
			return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
		}
		osTypeParam, err := url.PathUnescape(matches[regex.SubexpIndex("osType")])
		if err != nil {
			return nil, err
		}
		resp := a.srv.NewListPager(osTypeParam, nil)
		newListPager = &resp
		a.newListPager.add(req, newListPager)
		server.PagerResponderInjectNextLinks(newListPager, req, func(page *armhybridcompute.AgentVersionClientListResponse, createLink func() string) {
			page.NextLink = to.Ptr(createLink())
		})
	}
	resp, err := server.PagerResponderNext(newListPager, req)
	if err != nil {
		return nil, err
	}
	if !slices.Contains([]int{http.StatusOK}, resp.StatusCode) {
		a.newListPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newListPager) {
		a.newListPager.remove(req)
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to AgentVersionServerTransport
var agentVersionServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
