// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armslis

import "time"

// AmwAccount - Represents an Azure Monitor Workspace (AMW) account used for emitting metrics.
type AmwAccount struct {
	// REQUIRED; The ARM resource ID of the managed identity with access to the source account.
	Identity *string

	// REQUIRED; The ARM resource ID of the account where metrics are emitted.
	ResourceID *string
}

// Baseline - Defines the target parameters for a Slo baseline.
type Baseline struct {
	// REQUIRED; Specifies how evaluation is calculated, either based on calendar days or a rolling window.
	EvaluationCalculationType *EvaluationCalculationType

	// REQUIRED; The time frame (in days) used for SLI evaluation.
	EvaluationPeriodDays *int32

	// REQUIRED; The user-defined or Azure-defined target value used for comparison against the SLI value.
	Value *float32
}

// BaselineProperties - Defines the properties of a baseline.
type BaselineProperties struct {
	// REQUIRED; Defines the baseline target, which is compared against the SLI value to determine compliance.
	Baseline *Baseline
}

// Condition - Represents a filtering condition.
type Condition struct {
	// REQUIRED; Operator used in the filtering condition.
	Operator *ConditionOperator

	// REQUIRED; Value used in filtering.
	Value *string

	// Dimension name used in filtering.
	DimensionName *string

	// Defines the sampling type.
	SamplingType *SamplingType

	// Scalar function applied for filtering.
	ScalarFunction *ScalarFunction
}

// ExecutionState - Represents the current execution state of an SLI.
type ExecutionState struct {
	// REQUIRED; The execution state value.
	State *string

	// A descriptive message related to the execution state.
	Message *string
}

// ManagedServiceIdentity - Managed service identity (system assigned and/or user assigned identities)
type ManagedServiceIdentity struct {
	// REQUIRED; The type of managed identity assigned to this resource.
	Type *ManagedServiceIdentityType

	// The identities assigned to this resource by the user.
	UserAssignedIdentities map[string]*UserAssignedIdentity

	// READ-ONLY; The service principal ID of the system assigned identity. This property will only be provided for a system assigned
	// identity.
	PrincipalID *string

	// READ-ONLY; The tenant ID of the system assigned identity. This property will only be provided for a system assigned identity.
	TenantID *string
}

// Metric - Defines a metric in the destination AMW account.
type Metric struct {
	// REQUIRED; The name of the metric.
	MetricName *string

	// REQUIRED; The namespace of the metric.
	MetricNamespace *string
}

// Signal - Represents a signal model used in SLI calculations.
type Signal struct {
	// REQUIRED; Mathematical formula used to combine multiple metrics.
	SignalFormula *string

	// REQUIRED; Sources of metrics used for SLIs.
	SignalSources []*SignalSource
}

// SignalSource - Represents a signal source used in SLIs.
type SignalSource struct {
	// REQUIRED; Filters applied to modify signal values.
	Filters []*Condition

	// REQUIRED; Name of the metric.
	MetricName *string

	// REQUIRED; Namespace of the metric.
	MetricNamespace *string

	// REQUIRED; Unique identifier for the signal source.
	SignalSourceID *string

	// REQUIRED; Managed identity for authenticating the signal source.
	SourceAmwAccountManagedIdentity *string

	// REQUIRED; Resource ID of the source AMW account.
	SourceAmwAccountResourceID *string

	// REQUIRED; Defines how measurements are aggregated across multiple time series.
	SpatialAggregation *SpatialAggregation

	// REQUIRED; Defines how measurements are aggregated over a specific time window within the same time series.
	TemporalAggregation *TemporalAggregation
}

// Sli - Represents an SLI resource within the ProviderHub.
type Sli struct {
	// The managed service identities assigned to this resource.
	Identity *ManagedServiceIdentity

	// The resource-specific properties for this resource.
	Properties *SliResource

	// READ-ONLY; Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string

	// READ-ONLY; The name of the resource
	Name *string

	// READ-ONLY; Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData

	// READ-ONLY; The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string
}

// SliListResult - The response of a Sli list operation.
type SliListResult struct {
	// REQUIRED; The Sli items on this page
	Value []*Sli

	// The link to the next page of items
	NextLink *string
}

// SliProperties - Defines the properties of an SLI.
type SliProperties struct {
	// Represents good signals used in request-based SLI calculations.
	GoodSignals *Signal

	// Signals used for window-based SLI calculations.
	Signals *Signal

	// Represents total signals used in request-based SLI calculations.
	TotalSignals *Signal

	// Defines the uptime criteria for window-based SLIs.
	WindowUptimeCriteria *WindowUptimeCriteria
}

// SliResource - Defines the root level properties of an SLI resource.
type SliResource struct {
	// REQUIRED; Defines the SLO baseline associated with the SLI.
	BaselineProperties *BaselineProperties

	// REQUIRED; Specifies the category of the SLI, used to classify signals such as Availability and Latency.
	Category *Category

	// REQUIRED; A user-provided description of the SLI, with a maximum length of 1000 characters.
	Description *string

	// REQUIRED; Destination AMW accounts.
	DestinationAmwAccounts []*AmwAccount

	// REQUIRED; A flag to determine whether alert is enabled.
	EnableAlert *bool

	// REQUIRED; Determines how the SLI is evaluated—either based on request counts or time windows.
	EvaluationType *EvaluationType

	// REQUIRED; Defines the SLI properties associated with the SLI.
	SliProperties *SliProperties

	// READ-ONLY; The destination Azure Monitor Workspace (AMW) accounts where the SLI emits metrics.
	DestinationMetrics []*Metric

	// READ-ONLY; Indicates the current execution status of the SLI resource in ARM responses.
	ExecutionState *ExecutionState

	// READ-ONLY; Indicates the provisioning status of the last operation.
	ProvisioningState *ProvisioningState

	// READ-ONLY; The streaming rule Id associated with the Sli resource.
	StreamingRuleID *string

	// READ-ONLY; The streaming rule last updated timestamp associated with the Sli resource.
	StreamingRuleLastUpdatedTimestamp *time.Time
}

// SpatialAggregation - Represents the spatial aggregation model.
type SpatialAggregation struct {
	// REQUIRED; Dimensions considered for spatial aggregation.
	Dimensions []*string

	// REQUIRED; Type of spatial aggregation.
	Type *SpatialAggregationType
}

// SystemData - Metadata pertaining to creation and last modification of the resource.
type SystemData struct {
	// The timestamp of resource creation (UTC).
	CreatedAt *time.Time

	// The identity that created the resource.
	CreatedBy *string

	// The type of identity that created the resource.
	CreatedByType *CreatedByType

	// The timestamp of resource last modification (UTC)
	LastModifiedAt *time.Time

	// The identity that last modified the resource.
	LastModifiedBy *string

	// The type of identity that last modified the resource.
	LastModifiedByType *CreatedByType
}

// TemporalAggregation - Represents temporal aggregation settings.
type TemporalAggregation struct {
	// REQUIRED; Type of temporal aggregation.
	Type *TemporalAggregationType

	// Time window size for aggregation, in minutes.
	WindowSizeMinutes *int32
}

// UserAssignedIdentity - User assigned identity properties
type UserAssignedIdentity struct {
	// READ-ONLY; The client ID of the assigned identity.
	ClientID *string

	// READ-ONLY; The principal ID of the assigned identity.
	PrincipalID *string
}

// WindowUptimeCriteria - Represents criteria for determining uptime in window-based SLIs.
type WindowUptimeCriteria struct {
	// REQUIRED; Comparison operator used for uptime evaluation.
	Comparator *WindowUptimeCriteriaComparator

	// REQUIRED; Threshold value used to determine uptime.
	Target *float32
}

// executionMessage - Represents a KQL-M query execution message.
type executionMessage struct {
	// REQUIRED; The message documentation link.
	DocumentationLink *string

	// REQUIRED; The message severity.
	Severity *messageSeverity

	// REQUIRED; The message statement context.
	StatementContext *statementContextInformation

	// REQUIRED; The message text.
	Text *string
}

// kqlmQueryResult - Represents the result of a KQL-M query.
type kqlmQueryResult struct {
	// REQUIRED; The list of KQL-M query execution messages.
	ExecutionMessages []*executionMessage

	// REQUIRED; The query state.
	State *queryState

	// REQUIRED; The list of time series sets, where each set represents results for a query statement.
	TimeSeriesSets []*timeSeriesSet

	// The request ID.
	RequestID *string
}

// resultsMetadata - Represents metadata for a KQL-M query result.
type resultsMetadata struct {
	// REQUIRED; The data resolution of the KQL-M query result in HH:MM:SS format.
	DataResolution *string

	// REQUIRED; The number of datapoints in the KQL-M query result.
	DatapointsCount *int64

	// REQUIRED; The end time for the KQL-M query result.
	EndTimeUTC *time.Time

	// REQUIRED; The list of output dimensions of the KQL-M query result.
	ResultantDimensions []*string

	// REQUIRED; The list of output sampling types of the KQL-M query result.
	ResultantSamplingTypes []*samplingTypeProjection

	// REQUIRED; The start time for the KQL-M query result.
	StartTimeUTC *time.Time
}

// samplingTypesDataDictionary - Dictionary of sampling types to metric values.
type samplingTypesDataDictionary struct {
	// Error budget burn rate values.
	Burnrate []*float64

	// Downtime measurement values.
	Downtime []*float64

	// Count of good requests or events values.
	Good []*float64

	// Total count of requests or events values.
	Total []*float64

	// Uptime measurement values.
	Uptime []*float64

	// The calculated SLI value.
	Value []*float64
}

// signalPreviewSliProperties - Defines the properties for signal preview SLI.
type signalPreviewSliProperties struct {
	// REQUIRED; Determines how the SLI is evaluated—either based on request counts or time windows.
	EvaluationType *EvaluationType

	// REQUIRED; The preview type for the signal preview operation.
	PreviewType *previewType

	// Defines the SLO baseline associated with the SLI.
	BaselineProperties *BaselineProperties

	// Represents good signals used in request-based SLI calculations.
	GoodSignals *Signal

	// Signals used for window-based SLI calculations.
	Signals *Signal

	// Represents total signals used in request-based SLI calculations.
	TotalSignals *Signal

	// Defines the uptime criteria for window-based SLIs.
	WindowUptimeCriteria *WindowUptimeCriteria
}

// statementContextInformation - Represents statement context information for a message.
type statementContextInformation struct {
	// REQUIRED; The character position within the entire statement text where the error occurred.
	CharPositionAbsolute *int32

	// REQUIRED; The character position within that line where the error occurred.
	CharPositionInLine *int32

	// REQUIRED; Length of text section which caused an error.
	ErrorSectionLength *int32

	// REQUIRED; The line number in the input where the error occurred.
	LineNumber *int32
}

// timeSeriesData - Represents a time series data entry.
type timeSeriesData struct {
	// REQUIRED; The dictionary of dimension names to dimension values.
	DimensionValues map[string]*string

	// REQUIRED; The dictionary of sampling types to metric values (as list of doubles).
	SamplingTypesData *samplingTypesDataDictionary
}

// timeSeriesSet - Represents a set of time series results for a query statement.
type timeSeriesSet struct {
	// REQUIRED; The KQL-M query result metadata.
	ResultsMetadata *resultsMetadata

	// REQUIRED; The list of time series data.
	TimeSeriesData []*timeSeriesData
}
