// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armslis

import (
	"encoding/json"
	"fmt"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/datetime"
	"reflect"
	"time"
)

// MarshalJSON implements the json.Marshaller interface for type AmwAccount.
func (a AmwAccount) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "identity", a.Identity)
	populate(objectMap, "resourceId", a.ResourceID)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type AmwAccount.
func (a *AmwAccount) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", a, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "identity":
			err = unpopulate(val, "Identity", &a.Identity)
			delete(rawMsg, key)
		case "resourceId":
			err = unpopulate(val, "ResourceID", &a.ResourceID)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", a, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type Baseline.
func (b Baseline) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "evaluationCalculationType", b.EvaluationCalculationType)
	populate(objectMap, "evaluationPeriodDays", b.EvaluationPeriodDays)
	populate(objectMap, "value", b.Value)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type Baseline.
func (b *Baseline) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", b, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "evaluationCalculationType":
			err = unpopulate(val, "EvaluationCalculationType", &b.EvaluationCalculationType)
			delete(rawMsg, key)
		case "evaluationPeriodDays":
			err = unpopulate(val, "EvaluationPeriodDays", &b.EvaluationPeriodDays)
			delete(rawMsg, key)
		case "value":
			err = unpopulate(val, "Value", &b.Value)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", b, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type BaselineProperties.
func (b BaselineProperties) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "baseline", b.Baseline)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type BaselineProperties.
func (b *BaselineProperties) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", b, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "baseline":
			err = unpopulate(val, "Baseline", &b.Baseline)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", b, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type Condition.
func (c Condition) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "dimensionName", c.DimensionName)
	populate(objectMap, "operator", c.Operator)
	populate(objectMap, "samplingType", c.SamplingType)
	populate(objectMap, "scalarFunction", c.ScalarFunction)
	populate(objectMap, "value", c.Value)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type Condition.
func (c *Condition) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", c, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "dimensionName":
			err = unpopulate(val, "DimensionName", &c.DimensionName)
			delete(rawMsg, key)
		case "operator":
			err = unpopulate(val, "Operator", &c.Operator)
			delete(rawMsg, key)
		case "samplingType":
			err = unpopulate(val, "SamplingType", &c.SamplingType)
			delete(rawMsg, key)
		case "scalarFunction":
			err = unpopulate(val, "ScalarFunction", &c.ScalarFunction)
			delete(rawMsg, key)
		case "value":
			err = unpopulate(val, "Value", &c.Value)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", c, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type ExecutionState.
func (e ExecutionState) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "message", e.Message)
	populate(objectMap, "state", e.State)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type ExecutionState.
func (e *ExecutionState) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", e, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "message":
			err = unpopulate(val, "Message", &e.Message)
			delete(rawMsg, key)
		case "state":
			err = unpopulate(val, "State", &e.State)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", e, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type ManagedServiceIdentity.
func (m ManagedServiceIdentity) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "principalId", m.PrincipalID)
	populate(objectMap, "tenantId", m.TenantID)
	populate(objectMap, "type", m.Type)
	populate(objectMap, "userAssignedIdentities", m.UserAssignedIdentities)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type ManagedServiceIdentity.
func (m *ManagedServiceIdentity) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", m, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "principalId":
			err = unpopulate(val, "PrincipalID", &m.PrincipalID)
			delete(rawMsg, key)
		case "tenantId":
			err = unpopulate(val, "TenantID", &m.TenantID)
			delete(rawMsg, key)
		case "type":
			err = unpopulate(val, "Type", &m.Type)
			delete(rawMsg, key)
		case "userAssignedIdentities":
			err = unpopulate(val, "UserAssignedIdentities", &m.UserAssignedIdentities)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", m, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type Metric.
func (m Metric) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "metricName", m.MetricName)
	populate(objectMap, "metricNamespace", m.MetricNamespace)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type Metric.
func (m *Metric) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", m, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "metricName":
			err = unpopulate(val, "MetricName", &m.MetricName)
			delete(rawMsg, key)
		case "metricNamespace":
			err = unpopulate(val, "MetricNamespace", &m.MetricNamespace)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", m, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type Signal.
func (s Signal) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "signalFormula", s.SignalFormula)
	populate(objectMap, "signalSources", s.SignalSources)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type Signal.
func (s *Signal) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "signalFormula":
			err = unpopulate(val, "SignalFormula", &s.SignalFormula)
			delete(rawMsg, key)
		case "signalSources":
			err = unpopulate(val, "SignalSources", &s.SignalSources)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SignalSource.
func (s SignalSource) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "filters", s.Filters)
	populate(objectMap, "metricName", s.MetricName)
	populate(objectMap, "metricNamespace", s.MetricNamespace)
	populate(objectMap, "signalSourceId", s.SignalSourceID)
	populate(objectMap, "sourceAmwAccountManagedIdentity", s.SourceAmwAccountManagedIdentity)
	populate(objectMap, "sourceAmwAccountResourceId", s.SourceAmwAccountResourceID)
	populate(objectMap, "spatialAggregation", s.SpatialAggregation)
	populate(objectMap, "temporalAggregation", s.TemporalAggregation)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SignalSource.
func (s *SignalSource) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "filters":
			err = unpopulate(val, "Filters", &s.Filters)
			delete(rawMsg, key)
		case "metricName":
			err = unpopulate(val, "MetricName", &s.MetricName)
			delete(rawMsg, key)
		case "metricNamespace":
			err = unpopulate(val, "MetricNamespace", &s.MetricNamespace)
			delete(rawMsg, key)
		case "signalSourceId":
			err = unpopulate(val, "SignalSourceID", &s.SignalSourceID)
			delete(rawMsg, key)
		case "sourceAmwAccountManagedIdentity":
			err = unpopulate(val, "SourceAmwAccountManagedIdentity", &s.SourceAmwAccountManagedIdentity)
			delete(rawMsg, key)
		case "sourceAmwAccountResourceId":
			err = unpopulate(val, "SourceAmwAccountResourceID", &s.SourceAmwAccountResourceID)
			delete(rawMsg, key)
		case "spatialAggregation":
			err = unpopulate(val, "SpatialAggregation", &s.SpatialAggregation)
			delete(rawMsg, key)
		case "temporalAggregation":
			err = unpopulate(val, "TemporalAggregation", &s.TemporalAggregation)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type Sli.
func (s Sli) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "id", s.ID)
	populate(objectMap, "identity", s.Identity)
	populate(objectMap, "name", s.Name)
	populate(objectMap, "properties", s.Properties)
	populate(objectMap, "systemData", s.SystemData)
	populate(objectMap, "type", s.Type)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type Sli.
func (s *Sli) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "id":
			err = unpopulate(val, "ID", &s.ID)
			delete(rawMsg, key)
		case "identity":
			err = unpopulate(val, "Identity", &s.Identity)
			delete(rawMsg, key)
		case "name":
			err = unpopulate(val, "Name", &s.Name)
			delete(rawMsg, key)
		case "properties":
			err = unpopulate(val, "Properties", &s.Properties)
			delete(rawMsg, key)
		case "systemData":
			err = unpopulate(val, "SystemData", &s.SystemData)
			delete(rawMsg, key)
		case "type":
			err = unpopulate(val, "Type", &s.Type)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SliListResult.
func (s SliListResult) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "nextLink", s.NextLink)
	populate(objectMap, "value", s.Value)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SliListResult.
func (s *SliListResult) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "nextLink":
			err = unpopulate(val, "NextLink", &s.NextLink)
			delete(rawMsg, key)
		case "value":
			err = unpopulate(val, "Value", &s.Value)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SliProperties.
func (s SliProperties) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "goodSignals", s.GoodSignals)
	populate(objectMap, "signals", s.Signals)
	populate(objectMap, "totalSignals", s.TotalSignals)
	populate(objectMap, "windowUptimeCriteria", s.WindowUptimeCriteria)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SliProperties.
func (s *SliProperties) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "goodSignals":
			err = unpopulate(val, "GoodSignals", &s.GoodSignals)
			delete(rawMsg, key)
		case "signals":
			err = unpopulate(val, "Signals", &s.Signals)
			delete(rawMsg, key)
		case "totalSignals":
			err = unpopulate(val, "TotalSignals", &s.TotalSignals)
			delete(rawMsg, key)
		case "windowUptimeCriteria":
			err = unpopulate(val, "WindowUptimeCriteria", &s.WindowUptimeCriteria)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SliResource.
func (s SliResource) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "baselineProperties", s.BaselineProperties)
	populate(objectMap, "category", s.Category)
	populate(objectMap, "description", s.Description)
	populate(objectMap, "destinationAmwAccounts", s.DestinationAmwAccounts)
	populate(objectMap, "destinationMetrics", s.DestinationMetrics)
	populate(objectMap, "enableAlert", s.EnableAlert)
	populate(objectMap, "evaluationType", s.EvaluationType)
	populate(objectMap, "executionState", s.ExecutionState)
	populate(objectMap, "provisioningState", s.ProvisioningState)
	populate(objectMap, "sliProperties", s.SliProperties)
	populate(objectMap, "streamingRuleId", s.StreamingRuleID)
	populateTime[datetime.RFC3339](objectMap, "streamingRuleLastUpdatedTimestamp", s.StreamingRuleLastUpdatedTimestamp)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SliResource.
func (s *SliResource) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "baselineProperties":
			err = unpopulate(val, "BaselineProperties", &s.BaselineProperties)
			delete(rawMsg, key)
		case "category":
			err = unpopulate(val, "Category", &s.Category)
			delete(rawMsg, key)
		case "description":
			err = unpopulate(val, "Description", &s.Description)
			delete(rawMsg, key)
		case "destinationAmwAccounts":
			err = unpopulate(val, "DestinationAmwAccounts", &s.DestinationAmwAccounts)
			delete(rawMsg, key)
		case "destinationMetrics":
			err = unpopulate(val, "DestinationMetrics", &s.DestinationMetrics)
			delete(rawMsg, key)
		case "enableAlert":
			err = unpopulate(val, "EnableAlert", &s.EnableAlert)
			delete(rawMsg, key)
		case "evaluationType":
			err = unpopulate(val, "EvaluationType", &s.EvaluationType)
			delete(rawMsg, key)
		case "executionState":
			err = unpopulate(val, "ExecutionState", &s.ExecutionState)
			delete(rawMsg, key)
		case "provisioningState":
			err = unpopulate(val, "ProvisioningState", &s.ProvisioningState)
			delete(rawMsg, key)
		case "sliProperties":
			err = unpopulate(val, "SliProperties", &s.SliProperties)
			delete(rawMsg, key)
		case "streamingRuleId":
			err = unpopulate(val, "StreamingRuleID", &s.StreamingRuleID)
			delete(rawMsg, key)
		case "streamingRuleLastUpdatedTimestamp":
			err = unpopulateTime[datetime.RFC3339](val, "StreamingRuleLastUpdatedTimestamp", &s.StreamingRuleLastUpdatedTimestamp)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SpatialAggregation.
func (s SpatialAggregation) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "dimensions", s.Dimensions)
	populate(objectMap, "type", s.Type)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SpatialAggregation.
func (s *SpatialAggregation) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "dimensions":
			err = unpopulate(val, "Dimensions", &s.Dimensions)
			delete(rawMsg, key)
		case "type":
			err = unpopulate(val, "Type", &s.Type)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SystemData.
func (s SystemData) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populateTime[datetime.RFC3339](objectMap, "createdAt", s.CreatedAt)
	populate(objectMap, "createdBy", s.CreatedBy)
	populate(objectMap, "createdByType", s.CreatedByType)
	populateTime[datetime.RFC3339](objectMap, "lastModifiedAt", s.LastModifiedAt)
	populate(objectMap, "lastModifiedBy", s.LastModifiedBy)
	populate(objectMap, "lastModifiedByType", s.LastModifiedByType)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SystemData.
func (s *SystemData) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "createdAt":
			err = unpopulateTime[datetime.RFC3339](val, "CreatedAt", &s.CreatedAt)
			delete(rawMsg, key)
		case "createdBy":
			err = unpopulate(val, "CreatedBy", &s.CreatedBy)
			delete(rawMsg, key)
		case "createdByType":
			err = unpopulate(val, "CreatedByType", &s.CreatedByType)
			delete(rawMsg, key)
		case "lastModifiedAt":
			err = unpopulateTime[datetime.RFC3339](val, "LastModifiedAt", &s.LastModifiedAt)
			delete(rawMsg, key)
		case "lastModifiedBy":
			err = unpopulate(val, "LastModifiedBy", &s.LastModifiedBy)
			delete(rawMsg, key)
		case "lastModifiedByType":
			err = unpopulate(val, "LastModifiedByType", &s.LastModifiedByType)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type TemporalAggregation.
func (t TemporalAggregation) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "type", t.Type)
	populate(objectMap, "windowSizeMinutes", t.WindowSizeMinutes)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type TemporalAggregation.
func (t *TemporalAggregation) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", t, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "type":
			err = unpopulate(val, "Type", &t.Type)
			delete(rawMsg, key)
		case "windowSizeMinutes":
			err = unpopulate(val, "WindowSizeMinutes", &t.WindowSizeMinutes)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", t, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type UserAssignedIdentity.
func (u UserAssignedIdentity) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "clientId", u.ClientID)
	populate(objectMap, "principalId", u.PrincipalID)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type UserAssignedIdentity.
func (u *UserAssignedIdentity) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", u, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "clientId":
			err = unpopulate(val, "ClientID", &u.ClientID)
			delete(rawMsg, key)
		case "principalId":
			err = unpopulate(val, "PrincipalID", &u.PrincipalID)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", u, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type WindowUptimeCriteria.
func (w WindowUptimeCriteria) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "comparator", w.Comparator)
	populate(objectMap, "target", w.Target)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type WindowUptimeCriteria.
func (w *WindowUptimeCriteria) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", w, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "comparator":
			err = unpopulate(val, "Comparator", &w.Comparator)
			delete(rawMsg, key)
		case "target":
			err = unpopulate(val, "Target", &w.Target)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", w, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type executionMessage.
func (e executionMessage) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "documentationLink", e.DocumentationLink)
	populate(objectMap, "severity", e.Severity)
	populate(objectMap, "statementContext", e.StatementContext)
	populate(objectMap, "text", e.Text)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type executionMessage.
func (e *executionMessage) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", e, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "documentationLink":
			err = unpopulate(val, "DocumentationLink", &e.DocumentationLink)
			delete(rawMsg, key)
		case "severity":
			err = unpopulate(val, "Severity", &e.Severity)
			delete(rawMsg, key)
		case "statementContext":
			err = unpopulate(val, "StatementContext", &e.StatementContext)
			delete(rawMsg, key)
		case "text":
			err = unpopulate(val, "Text", &e.Text)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", e, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type kqlmQueryResult.
func (k kqlmQueryResult) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "executionMessages", k.ExecutionMessages)
	populate(objectMap, "requestId", k.RequestID)
	populate(objectMap, "state", k.State)
	populate(objectMap, "timeSeriesSets", k.TimeSeriesSets)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type kqlmQueryResult.
func (k *kqlmQueryResult) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", k, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "executionMessages":
			err = unpopulate(val, "ExecutionMessages", &k.ExecutionMessages)
			delete(rawMsg, key)
		case "requestId":
			err = unpopulate(val, "RequestID", &k.RequestID)
			delete(rawMsg, key)
		case "state":
			err = unpopulate(val, "State", &k.State)
			delete(rawMsg, key)
		case "timeSeriesSets":
			err = unpopulate(val, "TimeSeriesSets", &k.TimeSeriesSets)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", k, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type resultsMetadata.
func (r resultsMetadata) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "dataResolution", r.DataResolution)
	populate(objectMap, "datapointsCount", r.DatapointsCount)
	populateTime[datetime.RFC3339](objectMap, "endTimeUtc", r.EndTimeUTC)
	populate(objectMap, "resultantDimensions", r.ResultantDimensions)
	populate(objectMap, "resultantSamplingTypes", r.ResultantSamplingTypes)
	populateTime[datetime.RFC3339](objectMap, "startTimeUtc", r.StartTimeUTC)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type resultsMetadata.
func (r *resultsMetadata) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", r, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "dataResolution":
			err = unpopulate(val, "DataResolution", &r.DataResolution)
			delete(rawMsg, key)
		case "datapointsCount":
			err = unpopulate(val, "DatapointsCount", &r.DatapointsCount)
			delete(rawMsg, key)
		case "endTimeUtc":
			err = unpopulateTime[datetime.RFC3339](val, "EndTimeUTC", &r.EndTimeUTC)
			delete(rawMsg, key)
		case "resultantDimensions":
			err = unpopulate(val, "ResultantDimensions", &r.ResultantDimensions)
			delete(rawMsg, key)
		case "resultantSamplingTypes":
			err = unpopulate(val, "ResultantSamplingTypes", &r.ResultantSamplingTypes)
			delete(rawMsg, key)
		case "startTimeUtc":
			err = unpopulateTime[datetime.RFC3339](val, "StartTimeUTC", &r.StartTimeUTC)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", r, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type samplingTypesDataDictionary.
func (s samplingTypesDataDictionary) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "Burnrate", s.Burnrate)
	populate(objectMap, "Downtime", s.Downtime)
	populate(objectMap, "Good", s.Good)
	populate(objectMap, "Total", s.Total)
	populate(objectMap, "Uptime", s.Uptime)
	populate(objectMap, "Value", s.Value)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type samplingTypesDataDictionary.
func (s *samplingTypesDataDictionary) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "Burnrate":
			err = unpopulate(val, "Burnrate", &s.Burnrate)
			delete(rawMsg, key)
		case "Downtime":
			err = unpopulate(val, "Downtime", &s.Downtime)
			delete(rawMsg, key)
		case "Good":
			err = unpopulate(val, "Good", &s.Good)
			delete(rawMsg, key)
		case "Total":
			err = unpopulate(val, "Total", &s.Total)
			delete(rawMsg, key)
		case "Uptime":
			err = unpopulate(val, "Uptime", &s.Uptime)
			delete(rawMsg, key)
		case "Value":
			err = unpopulate(val, "Value", &s.Value)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type signalPreviewSliProperties.
func (s signalPreviewSliProperties) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "baselineProperties", s.BaselineProperties)
	populate(objectMap, "evaluationType", s.EvaluationType)
	populate(objectMap, "goodSignals", s.GoodSignals)
	populate(objectMap, "previewType", s.PreviewType)
	populate(objectMap, "signals", s.Signals)
	populate(objectMap, "totalSignals", s.TotalSignals)
	populate(objectMap, "windowUptimeCriteria", s.WindowUptimeCriteria)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type signalPreviewSliProperties.
func (s *signalPreviewSliProperties) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "baselineProperties":
			err = unpopulate(val, "BaselineProperties", &s.BaselineProperties)
			delete(rawMsg, key)
		case "evaluationType":
			err = unpopulate(val, "EvaluationType", &s.EvaluationType)
			delete(rawMsg, key)
		case "goodSignals":
			err = unpopulate(val, "GoodSignals", &s.GoodSignals)
			delete(rawMsg, key)
		case "previewType":
			err = unpopulate(val, "PreviewType", &s.PreviewType)
			delete(rawMsg, key)
		case "signals":
			err = unpopulate(val, "Signals", &s.Signals)
			delete(rawMsg, key)
		case "totalSignals":
			err = unpopulate(val, "TotalSignals", &s.TotalSignals)
			delete(rawMsg, key)
		case "windowUptimeCriteria":
			err = unpopulate(val, "WindowUptimeCriteria", &s.WindowUptimeCriteria)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type statementContextInformation.
func (s statementContextInformation) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "charPositionAbsolute", s.CharPositionAbsolute)
	populate(objectMap, "charPositionInLine", s.CharPositionInLine)
	populate(objectMap, "errorSectionLength", s.ErrorSectionLength)
	populate(objectMap, "lineNumber", s.LineNumber)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type statementContextInformation.
func (s *statementContextInformation) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "charPositionAbsolute":
			err = unpopulate(val, "CharPositionAbsolute", &s.CharPositionAbsolute)
			delete(rawMsg, key)
		case "charPositionInLine":
			err = unpopulate(val, "CharPositionInLine", &s.CharPositionInLine)
			delete(rawMsg, key)
		case "errorSectionLength":
			err = unpopulate(val, "ErrorSectionLength", &s.ErrorSectionLength)
			delete(rawMsg, key)
		case "lineNumber":
			err = unpopulate(val, "LineNumber", &s.LineNumber)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type timeSeriesData.
func (t timeSeriesData) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "dimensionValues", t.DimensionValues)
	populate(objectMap, "samplingTypesData", t.SamplingTypesData)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type timeSeriesData.
func (t *timeSeriesData) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", t, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "dimensionValues":
			err = unpopulate(val, "DimensionValues", &t.DimensionValues)
			delete(rawMsg, key)
		case "samplingTypesData":
			err = unpopulate(val, "SamplingTypesData", &t.SamplingTypesData)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", t, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type timeSeriesSet.
func (t timeSeriesSet) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "resultsMetadata", t.ResultsMetadata)
	populate(objectMap, "timeSeriesData", t.TimeSeriesData)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type timeSeriesSet.
func (t *timeSeriesSet) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", t, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "resultsMetadata":
			err = unpopulate(val, "ResultsMetadata", &t.ResultsMetadata)
			delete(rawMsg, key)
		case "timeSeriesData":
			err = unpopulate(val, "TimeSeriesData", &t.TimeSeriesData)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", t, err)
		}
	}
	return nil
}

func populate(m map[string]any, k string, v any) {
	if v == nil {
		return
	} else if azcore.IsNullValue(v) {
		m[k] = nil
	} else if !reflect.ValueOf(v).IsNil() {
		m[k] = v
	}
}

func populateTime[T dateTimeConstraints](m map[string]any, k string, t *time.Time) {
	if t == nil {
		return
	} else if azcore.IsNullValue(t) {
		m[k] = nil
	} else if !reflect.ValueOf(t).IsNil() {
		newTime := T(*t)
		m[k] = (*T)(&newTime)
	}
}

func unpopulate(data json.RawMessage, fn string, v any) error {
	if data == nil || string(data) == "null" {
		return nil
	}
	if err := json.Unmarshal(data, v); err != nil {
		return fmt.Errorf("struct field %s: %v", fn, err)
	}
	return nil
}

func unpopulateTime[T dateTimeConstraints](data json.RawMessage, fn string, t **time.Time) error {
	if data == nil || string(data) == "null" {
		return nil
	}
	var aux T
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("struct field %s: %v", fn, err)
	}
	newTime := time.Time(aux)
	*t = &newTime
	return nil
}

type dateTimeConstraints interface {
	datetime.PlainDate | datetime.PlainTime | datetime.RFC1123 | datetime.RFC3339 | datetime.Unix
}
