// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armslis

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// SloViewClient - Defines operations for previewing signal.
// Don't use this type directly, use NewSloViewClient() instead.
type SloViewClient struct {
	internal *arm.Client
}

// NewSloViewClient creates a new instance of SloViewClient with the specified values.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewSloViewClient(credential azcore.TokenCredential, options *arm.ClientOptions) (*SloViewClient, error) {
	cl, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	client := &SloViewClient{
		internal: cl,
	}
	return client, nil
}

// sliSignalPreview - Returns preview data for the signal.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-03-01-preview
//   - serviceGroupName - The name of the service group.
//   - body - The signal preview properties.
//   - options - sloViewClientsliSignalPreviewOptions contains the optional parameters for the SloViewClient.sliSignalPreview
//     method.
func (client *SloViewClient) sliSignalPreview(ctx context.Context, serviceGroupName string, body signalPreviewSliProperties, options *sloViewClientsliSignalPreviewOptions) (sloViewClientsliSignalPreviewResponse, error) {
	var err error
	const operationName = "SloViewClient.sliSignalPreview"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.sliSignalPreviewCreateRequest(ctx, serviceGroupName, body, options)
	if err != nil {
		return sloViewClientsliSignalPreviewResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return sloViewClientsliSignalPreviewResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return sloViewClientsliSignalPreviewResponse{}, err
	}
	resp, err := client.sliSignalPreviewHandleResponse(httpResp)
	return resp, err
}

// sliSignalPreviewCreateRequest creates the sliSignalPreview request.
func (client *SloViewClient) sliSignalPreviewCreateRequest(ctx context.Context, serviceGroupName string, body signalPreviewSliProperties, _ *sloViewClientsliSignalPreviewOptions) (*policy.Request, error) {
	urlPath := "/providers/Microsoft.Management/serviceGroups/{serviceGroupName}/providers/Microsoft.Monitor/sliSignalPreview"
	if serviceGroupName == "" {
		return nil, errors.New("parameter serviceGroupName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{serviceGroupName}", url.PathEscape(serviceGroupName))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-03-01-preview")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// sliSignalPreviewHandleResponse handles the sliSignalPreview response.
func (client *SloViewClient) sliSignalPreviewHandleResponse(resp *http.Response) (sloViewClientsliSignalPreviewResponse, error) {
	result := sloViewClientsliSignalPreviewResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.kqlmQueryResult); err != nil {
		return sloViewClientsliSignalPreviewResponse{}, err
	}
	return result, nil
}
