parameters:
  DependsOn: Build
  TestPipeline: false
  ServiceDirectory: ''

stages:
  - stage: Release
    variables:
      - template: /eng/pipelines/templates/variables/globals.yml
      - template: /eng/pipelines/templates/variables/image.yml
    dependsOn: ${{ parameters.DependsOn }}
    displayName: '[TEST] Release: ${{ parameters.ServiceDirectory }}'

    jobs:
      - job: TagRepository
        displayName: "[TEST] Create release tag"
        condition: and(succeeded(), ne(variables['Skip.TagRepository'], 'true'))

        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux

        steps:
          - checkout: self
          - download: current
            artifact: 'PackageInfo'
          - template: /eng/common/pipelines/templates/steps/retain-run.yml
          - template: /eng/common/pipelines/templates/steps/verify-restapi-spec-location.yml
            parameters:
              ${{ if startsWith(parameters.ServiceDirectory, '../') }}:
                PackageName: "${{replace(parameters.ServiceDirectory, '../', '')}}"
              ${{ else }}:
                PackageName: 'sdk/${{parameters.ServiceDirectory}}'
              ServiceDirectory: ${{parameters.ServiceDirectory}}
              ArtifactLocation: $(Pipeline.Workspace)
          - task: PowerShell@2
            displayName: 'Verify no replace directives in go.mod file'
            inputs:
              targetType: 'filePath'
              filePath: ./eng/scripts/validate_go_mod.ps1
              arguments: '${{ parameters.ServiceDirectory }}'
              pwsh: true
          - task: PowerShell@2
            displayName: 'Verify go.mod major version'
            inputs:
              targetType: 'filePath'
              filePath: ./eng/scripts/validate_go_mod_major_version.ps1
              arguments: '${{ parameters.ServiceDirectory }}'
              pwsh: true
          - download: current
            artifact: 'packages'
          - template: /eng/common/pipelines/templates/steps/set-default-branch.yml
            parameters:
              WorkingDirectory: $(Build.SourcesDirectory)
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'APIView prod deployment'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                . $(Build.SourcesDirectory)/eng/scripts/apiview-helpers.ps1
                New-APIViewFromCI `
                  -ServiceDirectory '${{ parameters.ServiceDirectory }}' `
                  -ArtifactPath '$(Pipeline.Workspace)/packages' `
                  -SourceBranch '$(Build.SourceBranchName)' `
                  -DefaultBranch '$(DefaultBranch)' `
                  -ConfigFileDir '$(Pipeline.Workspace)/packages/PackageInfo' `
                  -BuildId $(Build.BuildId) `
                  -RepoName '$(Build.Repository.Name)' `
                  -MarkPackageAsShipped $true
              pwsh: true
              workingDirectory: $(Pipeline.Workspace)
            displayName: Create API review for Go
            condition: and(succeeded(), ne(variables['Skip.CreateApiReview'], 'true'))
