// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/devhub/armdevhub"
	"net/http"
	"net/url"
	"reflect"
	"regexp"
	"slices"
)

// AdooAuthResponsesServer is a fake server for instances of the armdevhub.AdooAuthResponsesClient type.
type AdooAuthResponsesServer struct {
	// GetADOOAuthInfo is the fake for method AdooAuthResponsesClient.GetADOOAuthInfo
	// HTTP status codes to indicate success: http.StatusOK
	GetADOOAuthInfo func(ctx context.Context, location string, options *armdevhub.AdooAuthResponsesClientGetADOOAuthInfoOptions) (resp azfake.Responder[armdevhub.AdooAuthResponsesClientGetADOOAuthInfoResponse], errResp azfake.ErrorResponder)
}

// NewAdooAuthResponsesServerTransport creates a new instance of AdooAuthResponsesServerTransport with the provided implementation.
// The returned AdooAuthResponsesServerTransport instance is connected to an instance of armdevhub.AdooAuthResponsesClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewAdooAuthResponsesServerTransport(srv *AdooAuthResponsesServer) *AdooAuthResponsesServerTransport {
	return &AdooAuthResponsesServerTransport{srv: srv}
}

// AdooAuthResponsesServerTransport connects instances of armdevhub.AdooAuthResponsesClient to instances of AdooAuthResponsesServer.
// Don't use this type directly, use NewAdooAuthResponsesServerTransport instead.
type AdooAuthResponsesServerTransport struct {
	srv *AdooAuthResponsesServer
}

// Do implements the policy.Transporter interface for AdooAuthResponsesServerTransport.
func (a *AdooAuthResponsesServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return a.dispatchToMethodFake(req, method)
}

func (a *AdooAuthResponsesServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if adooAuthResponsesServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = adooAuthResponsesServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "AdooAuthResponsesClient.GetADOOAuthInfo":
				res.resp, res.err = a.dispatchGetADOOAuthInfo(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (a *AdooAuthResponsesServerTransport) dispatchGetADOOAuthInfo(req *http.Request) (*http.Response, error) {
	if a.srv.GetADOOAuthInfo == nil {
		return nil, &nonRetriableError{errors.New("fake for method GetADOOAuthInfo not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.DevHub/locations/(?P<location>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/adooauth/default/getADOOAuthInfo`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 3 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	body, err := server.UnmarshalRequestAsJSON[armdevhub.ADOOAuthCallRequest](req)
	if err != nil {
		return nil, err
	}
	locationParam, err := url.PathUnescape(matches[regex.SubexpIndex("location")])
	if err != nil {
		return nil, err
	}
	var options *armdevhub.AdooAuthResponsesClientGetADOOAuthInfoOptions
	if !reflect.ValueOf(body).IsZero() {
		options = &armdevhub.AdooAuthResponsesClientGetADOOAuthInfoOptions{
			Parameters: &body,
		}
	}
	respr, errRespr := a.srv.GetADOOAuthInfo(req.Context(), locationParam, options)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).ADOOAuthInfoResponse, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to AdooAuthResponsesServerTransport
var adooAuthResponsesServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
