// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/devhub/armdevhub"
	"net/http"
	"net/url"
	"reflect"
	"regexp"
	"slices"
)

// GitHubOAuthResponsesServer is a fake server for instances of the armdevhub.GitHubOAuthResponsesClient type.
type GitHubOAuthResponsesServer struct {
	// GitHubOAuth is the fake for method GitHubOAuthResponsesClient.GitHubOAuth
	// HTTP status codes to indicate success: http.StatusOK
	GitHubOAuth func(ctx context.Context, location string, options *armdevhub.GitHubOAuthResponsesClientGitHubOAuthOptions) (resp azfake.Responder[armdevhub.GitHubOAuthResponsesClientGitHubOAuthResponse], errResp azfake.ErrorResponder)

	// GitHubOAuthCallback is the fake for method GitHubOAuthResponsesClient.GitHubOAuthCallback
	// HTTP status codes to indicate success: http.StatusOK
	GitHubOAuthCallback func(ctx context.Context, location string, code string, state string, options *armdevhub.GitHubOAuthResponsesClientGitHubOAuthCallbackOptions) (resp azfake.Responder[armdevhub.GitHubOAuthResponsesClientGitHubOAuthCallbackResponse], errResp azfake.ErrorResponder)

	// ListGitHubOAuth is the fake for method GitHubOAuthResponsesClient.ListGitHubOAuth
	// HTTP status codes to indicate success: http.StatusOK
	ListGitHubOAuth func(ctx context.Context, location string, options *armdevhub.GitHubOAuthResponsesClientListGitHubOAuthOptions) (resp azfake.Responder[armdevhub.GitHubOAuthResponsesClientListGitHubOAuthResponse], errResp azfake.ErrorResponder)
}

// NewGitHubOAuthResponsesServerTransport creates a new instance of GitHubOAuthResponsesServerTransport with the provided implementation.
// The returned GitHubOAuthResponsesServerTransport instance is connected to an instance of armdevhub.GitHubOAuthResponsesClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewGitHubOAuthResponsesServerTransport(srv *GitHubOAuthResponsesServer) *GitHubOAuthResponsesServerTransport {
	return &GitHubOAuthResponsesServerTransport{srv: srv}
}

// GitHubOAuthResponsesServerTransport connects instances of armdevhub.GitHubOAuthResponsesClient to instances of GitHubOAuthResponsesServer.
// Don't use this type directly, use NewGitHubOAuthResponsesServerTransport instead.
type GitHubOAuthResponsesServerTransport struct {
	srv *GitHubOAuthResponsesServer
}

// Do implements the policy.Transporter interface for GitHubOAuthResponsesServerTransport.
func (g *GitHubOAuthResponsesServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return g.dispatchToMethodFake(req, method)
}

func (g *GitHubOAuthResponsesServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if gitHubOAuthResponsesServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = gitHubOAuthResponsesServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "GitHubOAuthResponsesClient.GitHubOAuth":
				res.resp, res.err = g.dispatchGitHubOAuth(req)
			case "GitHubOAuthResponsesClient.GitHubOAuthCallback":
				res.resp, res.err = g.dispatchGitHubOAuthCallback(req)
			case "GitHubOAuthResponsesClient.ListGitHubOAuth":
				res.resp, res.err = g.dispatchListGitHubOAuth(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (g *GitHubOAuthResponsesServerTransport) dispatchGitHubOAuth(req *http.Request) (*http.Response, error) {
	if g.srv.GitHubOAuth == nil {
		return nil, &nonRetriableError{errors.New("fake for method GitHubOAuth not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.DevHub/locations/(?P<location>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/githuboauth/default/getGitHubOAuthInfo`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 3 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	body, err := server.UnmarshalRequestAsJSON[armdevhub.GitHubOAuthCallRequest](req)
	if err != nil {
		return nil, err
	}
	locationParam, err := url.PathUnescape(matches[regex.SubexpIndex("location")])
	if err != nil {
		return nil, err
	}
	var options *armdevhub.GitHubOAuthResponsesClientGitHubOAuthOptions
	if !reflect.ValueOf(body).IsZero() {
		options = &armdevhub.GitHubOAuthResponsesClientGitHubOAuthOptions{
			Parameters: &body,
		}
	}
	respr, errRespr := g.srv.GitHubOAuth(req.Context(), locationParam, options)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).GitHubOAuthInfoResponse, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (g *GitHubOAuthResponsesServerTransport) dispatchGitHubOAuthCallback(req *http.Request) (*http.Response, error) {
	if g.srv.GitHubOAuthCallback == nil {
		return nil, &nonRetriableError{errors.New("fake for method GitHubOAuthCallback not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.DevHub/locations/(?P<location>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/githuboauth/default`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 3 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	qp := req.URL.Query()
	locationParam, err := url.PathUnescape(matches[regex.SubexpIndex("location")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := g.srv.GitHubOAuthCallback(req.Context(), locationParam, qp.Get("code"), qp.Get("state"), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).GitHubOAuthResponse, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (g *GitHubOAuthResponsesServerTransport) dispatchListGitHubOAuth(req *http.Request) (*http.Response, error) {
	if g.srv.ListGitHubOAuth == nil {
		return nil, &nonRetriableError{errors.New("fake for method ListGitHubOAuth not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.DevHub/locations/(?P<location>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/githuboauth`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 3 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	locationParam, err := url.PathUnescape(matches[regex.SubexpIndex("location")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := g.srv.ListGitHubOAuth(req.Context(), locationParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).GitHubOAuthListResponse, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to GitHubOAuthResponsesServerTransport
var gitHubOAuthResponsesServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
