// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/devhub/armdevhub"
	"net/http"
	"net/url"
	"regexp"
	"slices"
	"strings"
	"sync"
)

// Server is a fake server for instances of the armdevhub.Client type.
type Server struct {
	// ADOOAuthServer contains the fakes for client ADOOAuthClient
	ADOOAuthServer ADOOAuthServer

	// AdooAuthResponsesServer contains the fakes for client AdooAuthResponsesClient
	AdooAuthResponsesServer AdooAuthResponsesServer

	// GitHubOAuthResponsesServer contains the fakes for client GitHubOAuthResponsesClient
	GitHubOAuthResponsesServer GitHubOAuthResponsesServer

	// IacProfilesServer contains the fakes for client IacProfilesClient
	IacProfilesServer IacProfilesServer

	// OperationsServer contains the fakes for client OperationsClient
	OperationsServer OperationsServer

	// TemplateServer contains the fakes for client TemplateClient
	TemplateServer TemplateServer

	// VersionedTemplateServer contains the fakes for client VersionedTemplateClient
	VersionedTemplateServer VersionedTemplateServer

	// WorkflowServer contains the fakes for client WorkflowClient
	WorkflowServer WorkflowServer

	// GeneratePreviewArtifacts is the fake for method Client.GeneratePreviewArtifacts
	// HTTP status codes to indicate success: http.StatusOK
	GeneratePreviewArtifacts func(ctx context.Context, location string, parameters armdevhub.ArtifactGenerationProperties, options *armdevhub.ClientGeneratePreviewArtifactsOptions) (resp azfake.Responder[armdevhub.ClientGeneratePreviewArtifactsResponse], errResp azfake.ErrorResponder)
}

// NewServerTransport creates a new instance of ServerTransport with the provided implementation.
// The returned ServerTransport instance is connected to an instance of armdevhub.Client via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewServerTransport(srv *Server) *ServerTransport {
	return &ServerTransport{srv: srv}
}

// ServerTransport connects instances of armdevhub.Client to instances of Server.
// Don't use this type directly, use NewServerTransport instead.
type ServerTransport struct {
	srv                          *Server
	trMu                         sync.Mutex
	trADOOAuthServer             *ADOOAuthServerTransport
	trAdooAuthResponsesServer    *AdooAuthResponsesServerTransport
	trGitHubOAuthResponsesServer *GitHubOAuthResponsesServerTransport
	trIacProfilesServer          *IacProfilesServerTransport
	trOperationsServer           *OperationsServerTransport
	trTemplateServer             *TemplateServerTransport
	trVersionedTemplateServer    *VersionedTemplateServerTransport
	trWorkflowServer             *WorkflowServerTransport
}

// Do implements the policy.Transporter interface for ServerTransport.
func (s *ServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	if client := method[:strings.Index(method, ".")]; client != "Client" {
		return s.dispatchToClientFake(req, client)
	}
	return s.dispatchToMethodFake(req, method)
}

func (s *ServerTransport) dispatchToClientFake(req *http.Request, client string) (*http.Response, error) {
	var resp *http.Response
	var err error

	switch client {
	case "ADOOAuthClient":
		initServer(&s.trMu, &s.trADOOAuthServer, func() *ADOOAuthServerTransport {
			return NewADOOAuthServerTransport(&s.srv.ADOOAuthServer)
		})
		resp, err = s.trADOOAuthServer.Do(req)
	case "AdooAuthResponsesClient":
		initServer(&s.trMu, &s.trAdooAuthResponsesServer, func() *AdooAuthResponsesServerTransport {
			return NewAdooAuthResponsesServerTransport(&s.srv.AdooAuthResponsesServer)
		})
		resp, err = s.trAdooAuthResponsesServer.Do(req)
	case "GitHubOAuthResponsesClient":
		initServer(&s.trMu, &s.trGitHubOAuthResponsesServer, func() *GitHubOAuthResponsesServerTransport {
			return NewGitHubOAuthResponsesServerTransport(&s.srv.GitHubOAuthResponsesServer)
		})
		resp, err = s.trGitHubOAuthResponsesServer.Do(req)
	case "IacProfilesClient":
		initServer(&s.trMu, &s.trIacProfilesServer, func() *IacProfilesServerTransport {
			return NewIacProfilesServerTransport(&s.srv.IacProfilesServer)
		})
		resp, err = s.trIacProfilesServer.Do(req)
	case "OperationsClient":
		initServer(&s.trMu, &s.trOperationsServer, func() *OperationsServerTransport {
			return NewOperationsServerTransport(&s.srv.OperationsServer)
		})
		resp, err = s.trOperationsServer.Do(req)
	case "TemplateClient":
		initServer(&s.trMu, &s.trTemplateServer, func() *TemplateServerTransport {
			return NewTemplateServerTransport(&s.srv.TemplateServer)
		})
		resp, err = s.trTemplateServer.Do(req)
	case "VersionedTemplateClient":
		initServer(&s.trMu, &s.trVersionedTemplateServer, func() *VersionedTemplateServerTransport {
			return NewVersionedTemplateServerTransport(&s.srv.VersionedTemplateServer)
		})
		resp, err = s.trVersionedTemplateServer.Do(req)
	case "WorkflowClient":
		initServer(&s.trMu, &s.trWorkflowServer, func() *WorkflowServerTransport {
			return NewWorkflowServerTransport(&s.srv.WorkflowServer)
		})
		resp, err = s.trWorkflowServer.Do(req)
	default:
		err = fmt.Errorf("unhandled client %s", client)
	}

	return resp, err
}

func (s *ServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if serverTransportInterceptor != nil {
			res.resp, res.err, intercepted = serverTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "Client.GeneratePreviewArtifacts":
				res.resp, res.err = s.dispatchGeneratePreviewArtifacts(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (s *ServerTransport) dispatchGeneratePreviewArtifacts(req *http.Request) (*http.Response, error) {
	if s.srv.GeneratePreviewArtifacts == nil {
		return nil, &nonRetriableError{errors.New("fake for method GeneratePreviewArtifacts not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.DevHub/locations/(?P<location>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/generatePreviewArtifacts`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 3 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	body, err := server.UnmarshalRequestAsJSON[armdevhub.ArtifactGenerationProperties](req)
	if err != nil {
		return nil, err
	}
	locationParam, err := url.PathUnescape(matches[regex.SubexpIndex("location")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := s.srv.GeneratePreviewArtifacts(req.Context(), locationParam, body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).Value, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to ServerTransport
var serverTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
