// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"errors"
	"fmt"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"strings"
	"sync"
)

// ServerFactory is a fake server for instances of the armdevhub.ClientFactory type.
type ServerFactory struct {
	// ADOOAuthServer contains the fakes for client ADOOAuthClient
	ADOOAuthServer ADOOAuthServer

	// AdooAuthResponsesServer contains the fakes for client AdooAuthResponsesClient
	AdooAuthResponsesServer AdooAuthResponsesServer

	// Server contains the fakes for client Client
	Server Server

	// GitHubOAuthResponsesServer contains the fakes for client GitHubOAuthResponsesClient
	GitHubOAuthResponsesServer GitHubOAuthResponsesServer

	// IacProfilesServer contains the fakes for client IacProfilesClient
	IacProfilesServer IacProfilesServer

	// OperationsServer contains the fakes for client OperationsClient
	OperationsServer OperationsServer

	// TemplateServer contains the fakes for client TemplateClient
	TemplateServer TemplateServer

	// VersionedTemplateServer contains the fakes for client VersionedTemplateClient
	VersionedTemplateServer VersionedTemplateServer

	// WorkflowServer contains the fakes for client WorkflowClient
	WorkflowServer WorkflowServer
}

// NewServerFactoryTransport creates a new instance of ServerFactoryTransport with the provided implementation.
// The returned ServerFactoryTransport instance is connected to an instance of armdevhub.ClientFactory via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewServerFactoryTransport(srv *ServerFactory) *ServerFactoryTransport {
	return &ServerFactoryTransport{
		srv: srv,
	}
}

// ServerFactoryTransport connects instances of armdevhub.ClientFactory to instances of ServerFactory.
// Don't use this type directly, use NewServerFactoryTransport instead.
type ServerFactoryTransport struct {
	srv                          *ServerFactory
	trMu                         sync.Mutex
	trADOOAuthServer             *ADOOAuthServerTransport
	trAdooAuthResponsesServer    *AdooAuthResponsesServerTransport
	trServer                     *ServerTransport
	trGitHubOAuthResponsesServer *GitHubOAuthResponsesServerTransport
	trIacProfilesServer          *IacProfilesServerTransport
	trOperationsServer           *OperationsServerTransport
	trTemplateServer             *TemplateServerTransport
	trVersionedTemplateServer    *VersionedTemplateServerTransport
	trWorkflowServer             *WorkflowServerTransport
}

// Do implements the policy.Transporter interface for ServerFactoryTransport.
func (s *ServerFactoryTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	client := method[:strings.Index(method, ".")]
	var resp *http.Response
	var err error

	switch client {
	case "ADOOAuthClient":
		initServer(&s.trMu, &s.trADOOAuthServer, func() *ADOOAuthServerTransport { return NewADOOAuthServerTransport(&s.srv.ADOOAuthServer) })
		resp, err = s.trADOOAuthServer.Do(req)
	case "AdooAuthResponsesClient":
		initServer(&s.trMu, &s.trAdooAuthResponsesServer, func() *AdooAuthResponsesServerTransport {
			return NewAdooAuthResponsesServerTransport(&s.srv.AdooAuthResponsesServer)
		})
		resp, err = s.trAdooAuthResponsesServer.Do(req)
	case "Client":
		initServer(&s.trMu, &s.trServer, func() *ServerTransport { return NewServerTransport(&s.srv.Server) })
		resp, err = s.trServer.Do(req)
	case "GitHubOAuthResponsesClient":
		initServer(&s.trMu, &s.trGitHubOAuthResponsesServer, func() *GitHubOAuthResponsesServerTransport {
			return NewGitHubOAuthResponsesServerTransport(&s.srv.GitHubOAuthResponsesServer)
		})
		resp, err = s.trGitHubOAuthResponsesServer.Do(req)
	case "IacProfilesClient":
		initServer(&s.trMu, &s.trIacProfilesServer, func() *IacProfilesServerTransport { return NewIacProfilesServerTransport(&s.srv.IacProfilesServer) })
		resp, err = s.trIacProfilesServer.Do(req)
	case "OperationsClient":
		initServer(&s.trMu, &s.trOperationsServer, func() *OperationsServerTransport { return NewOperationsServerTransport(&s.srv.OperationsServer) })
		resp, err = s.trOperationsServer.Do(req)
	case "TemplateClient":
		initServer(&s.trMu, &s.trTemplateServer, func() *TemplateServerTransport { return NewTemplateServerTransport(&s.srv.TemplateServer) })
		resp, err = s.trTemplateServer.Do(req)
	case "VersionedTemplateClient":
		initServer(&s.trMu, &s.trVersionedTemplateServer, func() *VersionedTemplateServerTransport {
			return NewVersionedTemplateServerTransport(&s.srv.VersionedTemplateServer)
		})
		resp, err = s.trVersionedTemplateServer.Do(req)
	case "WorkflowClient":
		initServer(&s.trMu, &s.trWorkflowServer, func() *WorkflowServerTransport { return NewWorkflowServerTransport(&s.srv.WorkflowServer) })
		resp, err = s.trWorkflowServer.Do(req)
	default:
		err = fmt.Errorf("unhandled client %s", client)
	}

	if err != nil {
		return nil, err
	}

	return resp, nil
}
