// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armdevhub

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// AdooAuthResponsesClient contains the methods for the AdooAuthResponses group.
// Don't use this type directly, use NewAdooAuthResponsesClient() instead.
type AdooAuthResponsesClient struct {
	internal       *arm.Client
	subscriptionID string
}

// NewAdooAuthResponsesClient creates a new instance of AdooAuthResponsesClient with the specified values.
//   - subscriptionID - The ID of the target subscription. The value must be an UUID.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewAdooAuthResponsesClient(subscriptionID string, credential azcore.TokenCredential, options *arm.ClientOptions) (*AdooAuthResponsesClient, error) {
	cl, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	client := &AdooAuthResponsesClient{
		subscriptionID: subscriptionID,
		internal:       cl,
	}
	return client, nil
}

// GetADOOAuthInfo - Gets ADOOAuth info used to authenticate users with ADO.
//
// Gets ADOOAuth info used to authenticate users with ADO.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-03-01-preview
//   - location - The location name.
//   - options - AdooAuthResponsesClientGetADOOAuthInfoOptions contains the optional parameters for the AdooAuthResponsesClient.GetADOOAuthInfo
//     method.
func (client *AdooAuthResponsesClient) GetADOOAuthInfo(ctx context.Context, location string, options *AdooAuthResponsesClientGetADOOAuthInfoOptions) (AdooAuthResponsesClientGetADOOAuthInfoResponse, error) {
	var err error
	const operationName = "AdooAuthResponsesClient.GetADOOAuthInfo"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getADOOAuthInfoCreateRequest(ctx, location, options)
	if err != nil {
		return AdooAuthResponsesClientGetADOOAuthInfoResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return AdooAuthResponsesClientGetADOOAuthInfoResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return AdooAuthResponsesClientGetADOOAuthInfoResponse{}, err
	}
	resp, err := client.getADOOAuthInfoHandleResponse(httpResp)
	return resp, err
}

// getADOOAuthInfoCreateRequest creates the GetADOOAuthInfo request.
func (client *AdooAuthResponsesClient) getADOOAuthInfoCreateRequest(ctx context.Context, location string, options *AdooAuthResponsesClientGetADOOAuthInfoOptions) (*policy.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/providers/Microsoft.DevHub/locations/{location}/adooauth/default/getADOOAuthInfo"
	if client.subscriptionID == "" {
		return nil, errors.New("parameter client.subscriptionID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	if location == "" {
		return nil, errors.New("parameter location cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{location}", url.PathEscape(location))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-03-01-preview")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.Parameters != nil {
		req.Raw().Header["Content-Type"] = []string{"application/json"}
		if err := runtime.MarshalAsJSON(req, *options.Parameters); err != nil {
			return nil, err
		}
		return req, nil
	}
	return req, nil
}

// getADOOAuthInfoHandleResponse handles the GetADOOAuthInfo response.
func (client *AdooAuthResponsesClient) getADOOAuthInfoHandleResponse(resp *http.Response) (AdooAuthResponsesClientGetADOOAuthInfoResponse, error) {
	result := AdooAuthResponsesClientGetADOOAuthInfoResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.ADOOAuthInfoResponse); err != nil {
		return AdooAuthResponsesClientGetADOOAuthInfoResponse{}, err
	}
	return result, nil
}
