// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armdevhub

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// Client - The AKS Developer Hub Service Client
// Don't use this type directly, use NewClient() instead.
type Client struct {
	internal       *arm.Client
	subscriptionID string
}

// NewClient creates a new instance of Client with the specified values.
//   - subscriptionID - The ID of the target subscription. The value must be an UUID.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewClient(subscriptionID string, credential azcore.TokenCredential, options *arm.ClientOptions) (*Client, error) {
	cl, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	client := &Client{
		subscriptionID: subscriptionID,
		internal:       cl,
	}
	return client, nil
}

// NewADOOAuthClient creates a new instance of [ADOOAuthClient].
func (client *Client) NewADOOAuthClient() *ADOOAuthClient {
	return &ADOOAuthClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewAdooAuthResponsesClient creates a new instance of [AdooAuthResponsesClient].
func (client *Client) NewAdooAuthResponsesClient() *AdooAuthResponsesClient {
	return &AdooAuthResponsesClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewGitHubOAuthResponsesClient creates a new instance of [GitHubOAuthResponsesClient].
func (client *Client) NewGitHubOAuthResponsesClient() *GitHubOAuthResponsesClient {
	return &GitHubOAuthResponsesClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewIacProfilesClient creates a new instance of [IacProfilesClient].
func (client *Client) NewIacProfilesClient() *IacProfilesClient {
	return &IacProfilesClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewOperationsClient creates a new instance of [OperationsClient].
func (client *Client) NewOperationsClient() *OperationsClient {
	return &OperationsClient{
		internal: client.internal,
	}
}

// NewTemplateClient creates a new instance of [TemplateClient].
func (client *Client) NewTemplateClient() *TemplateClient {
	return &TemplateClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewVersionedTemplateClient creates a new instance of [VersionedTemplateClient].
func (client *Client) NewVersionedTemplateClient() *VersionedTemplateClient {
	return &VersionedTemplateClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewWorkflowClient creates a new instance of [WorkflowClient].
func (client *Client) NewWorkflowClient() *WorkflowClient {
	return &WorkflowClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// GeneratePreviewArtifacts - Generate preview dockerfile and manifests.
//
// Generate preview dockerfile and manifests.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-03-01-preview
//   - location - The location name.
//   - options - ClientGeneratePreviewArtifactsOptions contains the optional parameters for the Client.GeneratePreviewArtifacts
//     method.
func (client *Client) GeneratePreviewArtifacts(ctx context.Context, location string, parameters ArtifactGenerationProperties, options *ClientGeneratePreviewArtifactsOptions) (ClientGeneratePreviewArtifactsResponse, error) {
	var err error
	const operationName = "Client.GeneratePreviewArtifacts"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.generatePreviewArtifactsCreateRequest(ctx, location, parameters, options)
	if err != nil {
		return ClientGeneratePreviewArtifactsResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return ClientGeneratePreviewArtifactsResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return ClientGeneratePreviewArtifactsResponse{}, err
	}
	resp, err := client.generatePreviewArtifactsHandleResponse(httpResp)
	return resp, err
}

// generatePreviewArtifactsCreateRequest creates the GeneratePreviewArtifacts request.
func (client *Client) generatePreviewArtifactsCreateRequest(ctx context.Context, location string, parameters ArtifactGenerationProperties, _ *ClientGeneratePreviewArtifactsOptions) (*policy.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/providers/Microsoft.DevHub/locations/{location}/generatePreviewArtifacts"
	if client.subscriptionID == "" {
		return nil, errors.New("parameter client.subscriptionID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	if location == "" {
		return nil, errors.New("parameter location cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{location}", url.PathEscape(location))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-03-01-preview")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, parameters); err != nil {
		return nil, err
	}
	return req, nil
}

// generatePreviewArtifactsHandleResponse handles the GeneratePreviewArtifacts response.
func (client *Client) generatePreviewArtifactsHandleResponse(resp *http.Response) (ClientGeneratePreviewArtifactsResponse, error) {
	result := ClientGeneratePreviewArtifactsResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.Value); err != nil {
		return ClientGeneratePreviewArtifactsResponse{}, err
	}
	return result, nil
}
