// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armdevhub

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// GitHubOAuthResponsesClient contains the methods for the GitHubOAuthResponses group.
// Don't use this type directly, use NewGitHubOAuthResponsesClient() instead.
type GitHubOAuthResponsesClient struct {
	internal       *arm.Client
	subscriptionID string
}

// NewGitHubOAuthResponsesClient creates a new instance of GitHubOAuthResponsesClient with the specified values.
//   - subscriptionID - The ID of the target subscription. The value must be an UUID.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewGitHubOAuthResponsesClient(subscriptionID string, credential azcore.TokenCredential, options *arm.ClientOptions) (*GitHubOAuthResponsesClient, error) {
	cl, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	client := &GitHubOAuthResponsesClient{
		subscriptionID: subscriptionID,
		internal:       cl,
	}
	return client, nil
}

// GitHubOAuth - Gets GitHubOAuth info used to authenticate users with the Developer Hub GitHub App.
//
// Gets GitHubOAuth info used to authenticate users with the Developer Hub GitHub App.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-03-01-preview
//   - location - The location name.
//   - options - GitHubOAuthResponsesClientGitHubOAuthOptions contains the optional parameters for the GitHubOAuthResponsesClient.GitHubOAuth
//     method.
func (client *GitHubOAuthResponsesClient) GitHubOAuth(ctx context.Context, location string, options *GitHubOAuthResponsesClientGitHubOAuthOptions) (GitHubOAuthResponsesClientGitHubOAuthResponse, error) {
	var err error
	const operationName = "GitHubOAuthResponsesClient.GitHubOAuth"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.gitHubOAuthCreateRequest(ctx, location, options)
	if err != nil {
		return GitHubOAuthResponsesClientGitHubOAuthResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return GitHubOAuthResponsesClientGitHubOAuthResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return GitHubOAuthResponsesClientGitHubOAuthResponse{}, err
	}
	resp, err := client.gitHubOAuthHandleResponse(httpResp)
	return resp, err
}

// gitHubOAuthCreateRequest creates the GitHubOAuth request.
func (client *GitHubOAuthResponsesClient) gitHubOAuthCreateRequest(ctx context.Context, location string, options *GitHubOAuthResponsesClientGitHubOAuthOptions) (*policy.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/providers/Microsoft.DevHub/locations/{location}/githuboauth/default/getGitHubOAuthInfo"
	if client.subscriptionID == "" {
		return nil, errors.New("parameter client.subscriptionID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	if location == "" {
		return nil, errors.New("parameter location cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{location}", url.PathEscape(location))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-03-01-preview")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.Parameters != nil {
		req.Raw().Header["Content-Type"] = []string{"application/json"}
		if err := runtime.MarshalAsJSON(req, *options.Parameters); err != nil {
			return nil, err
		}
		return req, nil
	}
	return req, nil
}

// gitHubOAuthHandleResponse handles the GitHubOAuth response.
func (client *GitHubOAuthResponsesClient) gitHubOAuthHandleResponse(resp *http.Response) (GitHubOAuthResponsesClientGitHubOAuthResponse, error) {
	result := GitHubOAuthResponsesClientGitHubOAuthResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.GitHubOAuthInfoResponse); err != nil {
		return GitHubOAuthResponsesClientGitHubOAuthResponse{}, err
	}
	return result, nil
}

// GitHubOAuthCallback - Callback URL to hit once authenticated with GitHub App to have the service store the OAuth token.
//
// Callback URL to hit once authenticated with GitHub App to have the service store the OAuth token.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-03-01-preview
//   - location - The location name.
//   - code - The code response from authenticating the GitHub App.
//   - state - The state response from authenticating the GitHub App.
//   - options - GitHubOAuthResponsesClientGitHubOAuthCallbackOptions contains the optional parameters for the GitHubOAuthResponsesClient.GitHubOAuthCallback
//     method.
func (client *GitHubOAuthResponsesClient) GitHubOAuthCallback(ctx context.Context, location string, code string, state string, options *GitHubOAuthResponsesClientGitHubOAuthCallbackOptions) (GitHubOAuthResponsesClientGitHubOAuthCallbackResponse, error) {
	var err error
	const operationName = "GitHubOAuthResponsesClient.GitHubOAuthCallback"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.gitHubOAuthCallbackCreateRequest(ctx, location, code, state, options)
	if err != nil {
		return GitHubOAuthResponsesClientGitHubOAuthCallbackResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return GitHubOAuthResponsesClientGitHubOAuthCallbackResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return GitHubOAuthResponsesClientGitHubOAuthCallbackResponse{}, err
	}
	resp, err := client.gitHubOAuthCallbackHandleResponse(httpResp)
	return resp, err
}

// gitHubOAuthCallbackCreateRequest creates the GitHubOAuthCallback request.
func (client *GitHubOAuthResponsesClient) gitHubOAuthCallbackCreateRequest(ctx context.Context, location string, code string, state string, _ *GitHubOAuthResponsesClientGitHubOAuthCallbackOptions) (*policy.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/providers/Microsoft.DevHub/locations/{location}/githuboauth/default"
	if client.subscriptionID == "" {
		return nil, errors.New("parameter client.subscriptionID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	if location == "" {
		return nil, errors.New("parameter location cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{location}", url.PathEscape(location))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-03-01-preview")
	reqQP.Set("code", code)
	reqQP.Set("state", state)
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// gitHubOAuthCallbackHandleResponse handles the GitHubOAuthCallback response.
func (client *GitHubOAuthResponsesClient) gitHubOAuthCallbackHandleResponse(resp *http.Response) (GitHubOAuthResponsesClientGitHubOAuthCallbackResponse, error) {
	result := GitHubOAuthResponsesClientGitHubOAuthCallbackResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.GitHubOAuthResponse); err != nil {
		return GitHubOAuthResponsesClientGitHubOAuthCallbackResponse{}, err
	}
	return result, nil
}

// ListGitHubOAuth - Callback URL to hit once authenticated with GitHub App to have the service store the OAuth token.
//
// Callback URL to hit once authenticated with GitHub App to have the service store the OAuth token.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-03-01-preview
//   - location - The location name.
//   - options - GitHubOAuthResponsesClientListGitHubOAuthOptions contains the optional parameters for the GitHubOAuthResponsesClient.ListGitHubOAuth
//     method.
func (client *GitHubOAuthResponsesClient) ListGitHubOAuth(ctx context.Context, location string, options *GitHubOAuthResponsesClientListGitHubOAuthOptions) (GitHubOAuthResponsesClientListGitHubOAuthResponse, error) {
	var err error
	const operationName = "GitHubOAuthResponsesClient.ListGitHubOAuth"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.listGitHubOAuthCreateRequest(ctx, location, options)
	if err != nil {
		return GitHubOAuthResponsesClientListGitHubOAuthResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return GitHubOAuthResponsesClientListGitHubOAuthResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return GitHubOAuthResponsesClientListGitHubOAuthResponse{}, err
	}
	resp, err := client.listGitHubOAuthHandleResponse(httpResp)
	return resp, err
}

// listGitHubOAuthCreateRequest creates the ListGitHubOAuth request.
func (client *GitHubOAuthResponsesClient) listGitHubOAuthCreateRequest(ctx context.Context, location string, _ *GitHubOAuthResponsesClientListGitHubOAuthOptions) (*policy.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/providers/Microsoft.DevHub/locations/{location}/githuboauth"
	if client.subscriptionID == "" {
		return nil, errors.New("parameter client.subscriptionID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	if location == "" {
		return nil, errors.New("parameter location cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{location}", url.PathEscape(location))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-03-01-preview")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// listGitHubOAuthHandleResponse handles the ListGitHubOAuth response.
func (client *GitHubOAuthResponsesClient) listGitHubOAuthHandleResponse(resp *http.Response) (GitHubOAuthResponsesClientListGitHubOAuthResponse, error) {
	result := GitHubOAuthResponsesClientListGitHubOAuthResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.GitHubOAuthListResponse); err != nil {
		return GitHubOAuthResponsesClientListGitHubOAuthResponse{}, err
	}
	return result, nil
}
