// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armdevhub_test

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/devhub/armdevhub"
	"log"
)

// Generated from example definition: 2025-03-01-preview/GitHubOAuth.json
func ExampleGitHubOAuthResponsesClient_GitHubOAuth() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armdevhub.NewClientFactory("00000000-0000-0000-0000-000000000000", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewGitHubOAuthResponsesClient().GitHubOAuth(ctx, "eastus2euap", &armdevhub.GitHubOAuthResponsesClientGitHubOAuthOptions{
		Parameters: &armdevhub.GitHubOAuthCallRequest{
			RedirectURL: to.Ptr("https://ms.portal.azure.com/aks"),
		}})
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armdevhub.GitHubOAuthResponsesClientGitHubOAuthResponse{
	// 	GitHubOAuthInfoResponse: armdevhub.GitHubOAuthInfoResponse{
	// 		AuthURL: to.Ptr("https://github.com/login/oauth/authorize?client_id=11111111&redirect_uri=https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.DevHub/locations/eastus2euap/githuboauth&state=2345678-3456-7890-5678-012345678901&scope=repo,user:email,workflow"),
	// 		Token: to.Ptr(""),
	// 	},
	// }
}

// Generated from example definition: 2025-03-01-preview/GitHubOAuthCallback.json
func ExampleGitHubOAuthResponsesClient_GitHubOAuthCallback() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armdevhub.NewClientFactory("00000000-0000-0000-0000-000000000000", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewGitHubOAuthResponsesClient().GitHubOAuthCallback(ctx, "eastus2euap", "3584d83530557fdd1f46af8289938c8ef79f9dc5", "12345678-3456-7890-5678-012345678901", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armdevhub.GitHubOAuthResponsesClientGitHubOAuthCallbackResponse{
	// 	GitHubOAuthResponse: armdevhub.GitHubOAuthResponse{
	// 		Name: to.Ptr("default"),
	// 		Type: to.Ptr("Microsoft.DevHub/locations/githuboauth"),
	// 		ID: to.Ptr("/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.DevHub/locations/eastus2euap/githuboauth/default"),
	// 		Properties: &armdevhub.GitHubOAuthProperties{
	// 			Username: to.Ptr("user"),
	// 		},
	// 	},
	// }
}

// Generated from example definition: 2025-03-01-preview/GitHubOAuth_List.json
func ExampleGitHubOAuthResponsesClient_ListGitHubOAuth() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armdevhub.NewClientFactory("00000000-0000-0000-0000-000000000000", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewGitHubOAuthResponsesClient().ListGitHubOAuth(ctx, "eastus2euap", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armdevhub.GitHubOAuthResponsesClientListGitHubOAuthResponse{
	// 	GitHubOAuthListResponse: armdevhub.GitHubOAuthListResponse{
	// 		Value: []*armdevhub.GitHubOAuthResponse{
	// 			{
	// 				Name: to.Ptr("default"),
	// 				Type: to.Ptr("Microsoft.DevHub/locations/githuboauth"),
	// 				ID: to.Ptr("/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.DevHub/locations/eastus2euap/githuboauth/default"),
	// 				Properties: &armdevhub.GitHubOAuthProperties{
	// 					Username: to.Ptr("user"),
	// 				},
	// 			},
	// 		},
	// 	},
	// }
}
