// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor"
	"net/http"
	"net/url"
	"regexp"
)

// MetricAlertsStatusServer is a fake server for instances of the armmonitor.MetricAlertsStatusClient type.
type MetricAlertsStatusServer struct {
	// NewListPager is the fake for method MetricAlertsStatusClient.NewListPager
	// HTTP status codes to indicate success: http.StatusOK
	NewListPager func(resourceGroupName string, ruleName string, options *armmonitor.MetricAlertsStatusClientListOptions) (resp azfake.PagerResponder[armmonitor.MetricAlertsStatusClientListResponse])

	// NewListByNamePager is the fake for method MetricAlertsStatusClient.NewListByNamePager
	// HTTP status codes to indicate success: http.StatusOK
	NewListByNamePager func(resourceGroupName string, ruleName string, statusName string, options *armmonitor.MetricAlertsStatusClientListByNameOptions) (resp azfake.PagerResponder[armmonitor.MetricAlertsStatusClientListByNameResponse])
}

// NewMetricAlertsStatusServerTransport creates a new instance of MetricAlertsStatusServerTransport with the provided implementation.
// The returned MetricAlertsStatusServerTransport instance is connected to an instance of armmonitor.MetricAlertsStatusClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewMetricAlertsStatusServerTransport(srv *MetricAlertsStatusServer) *MetricAlertsStatusServerTransport {
	return &MetricAlertsStatusServerTransport{
		srv:                srv,
		newListPager:       newTracker[azfake.PagerResponder[armmonitor.MetricAlertsStatusClientListResponse]](),
		newListByNamePager: newTracker[azfake.PagerResponder[armmonitor.MetricAlertsStatusClientListByNameResponse]](),
	}
}

// MetricAlertsStatusServerTransport connects instances of armmonitor.MetricAlertsStatusClient to instances of MetricAlertsStatusServer.
// Don't use this type directly, use NewMetricAlertsStatusServerTransport instead.
type MetricAlertsStatusServerTransport struct {
	srv                *MetricAlertsStatusServer
	newListPager       *tracker[azfake.PagerResponder[armmonitor.MetricAlertsStatusClientListResponse]]
	newListByNamePager *tracker[azfake.PagerResponder[armmonitor.MetricAlertsStatusClientListByNameResponse]]
}

// Do implements the policy.Transporter interface for MetricAlertsStatusServerTransport.
func (m *MetricAlertsStatusServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return m.dispatchToMethodFake(req, method)
}

func (m *MetricAlertsStatusServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result)
	defer close(resultChan)

	go func() {
		var intercepted bool
		var res result
		if metricAlertsStatusServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = metricAlertsStatusServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "MetricAlertsStatusClient.NewListPager":
				res.resp, res.err = m.dispatchNewListPager(req)
			case "MetricAlertsStatusClient.NewListByNamePager":
				res.resp, res.err = m.dispatchNewListByNamePager(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		select {
		case resultChan <- res:
		case <-req.Context().Done():
		}
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (m *MetricAlertsStatusServerTransport) dispatchNewListPager(req *http.Request) (*http.Response, error) {
	if m.srv.NewListPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewListPager not implemented")}
	}
	newListPager := m.newListPager.get(req)
	if newListPager == nil {
		const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/resourcegroups/(?P<resourceGroupName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.Insights/metricAlerts/(?P<ruleName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/status`
		regex := regexp.MustCompile(regexStr)
		matches := regex.FindStringSubmatch(req.URL.EscapedPath())
		if len(matches) < 4 {
			return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
		}
		resourceGroupNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("resourceGroupName")])
		if err != nil {
			return nil, err
		}
		ruleNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("ruleName")])
		if err != nil {
			return nil, err
		}
		resp := m.srv.NewListPager(resourceGroupNameParam, ruleNameParam, nil)
		newListPager = &resp
		m.newListPager.add(req, newListPager)
	}
	resp, err := server.PagerResponderNext(newListPager, req)
	if err != nil {
		return nil, err
	}
	if !contains([]int{http.StatusOK}, resp.StatusCode) {
		m.newListPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newListPager) {
		m.newListPager.remove(req)
	}
	return resp, nil
}

func (m *MetricAlertsStatusServerTransport) dispatchNewListByNamePager(req *http.Request) (*http.Response, error) {
	if m.srv.NewListByNamePager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewListByNamePager not implemented")}
	}
	newListByNamePager := m.newListByNamePager.get(req)
	if newListByNamePager == nil {
		const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/resourceGroups/(?P<resourceGroupName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.Insights/metricAlerts/(?P<ruleName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/status/(?P<statusName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
		regex := regexp.MustCompile(regexStr)
		matches := regex.FindStringSubmatch(req.URL.EscapedPath())
		if len(matches) < 5 {
			return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
		}
		resourceGroupNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("resourceGroupName")])
		if err != nil {
			return nil, err
		}
		ruleNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("ruleName")])
		if err != nil {
			return nil, err
		}
		statusNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("statusName")])
		if err != nil {
			return nil, err
		}
		resp := m.srv.NewListByNamePager(resourceGroupNameParam, ruleNameParam, statusNameParam, nil)
		newListByNamePager = &resp
		m.newListByNamePager.add(req, newListByNamePager)
	}
	resp, err := server.PagerResponderNext(newListByNamePager, req)
	if err != nil {
		return nil, err
	}
	if !contains([]int{http.StatusOK}, resp.StatusCode) {
		m.newListByNamePager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newListByNamePager) {
		m.newListByNamePager.remove(req)
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to MetricAlertsStatusServerTransport
var metricAlertsStatusServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
