// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity"
	"net/http"
	"slices"
)

// SensitivitySettingsServer is a fake server for instances of the armsecurity.SensitivitySettingsClient type.
type SensitivitySettingsServer struct {
	// CreateOrUpdate is the fake for method SensitivitySettingsClient.CreateOrUpdate
	// HTTP status codes to indicate success: http.StatusOK
	CreateOrUpdate func(ctx context.Context, sensitivitySettings armsecurity.UpdateSensitivitySettingsRequest, options *armsecurity.SensitivitySettingsClientCreateOrUpdateOptions) (resp azfake.Responder[armsecurity.SensitivitySettingsClientCreateOrUpdateResponse], errResp azfake.ErrorResponder)

	// Get is the fake for method SensitivitySettingsClient.Get
	// HTTP status codes to indicate success: http.StatusOK
	Get func(ctx context.Context, options *armsecurity.SensitivitySettingsClientGetOptions) (resp azfake.Responder[armsecurity.SensitivitySettingsClientGetResponse], errResp azfake.ErrorResponder)

	// NewListPager is the fake for method SensitivitySettingsClient.NewListPager
	// HTTP status codes to indicate success: http.StatusOK
	NewListPager func(options *armsecurity.SensitivitySettingsClientListOptions) (resp azfake.PagerResponder[armsecurity.SensitivitySettingsClientListResponse])
}

// NewSensitivitySettingsServerTransport creates a new instance of SensitivitySettingsServerTransport with the provided implementation.
// The returned SensitivitySettingsServerTransport instance is connected to an instance of armsecurity.SensitivitySettingsClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewSensitivitySettingsServerTransport(srv *SensitivitySettingsServer) *SensitivitySettingsServerTransport {
	return &SensitivitySettingsServerTransport{
		srv:          srv,
		newListPager: newTracker[azfake.PagerResponder[armsecurity.SensitivitySettingsClientListResponse]](),
	}
}

// SensitivitySettingsServerTransport connects instances of armsecurity.SensitivitySettingsClient to instances of SensitivitySettingsServer.
// Don't use this type directly, use NewSensitivitySettingsServerTransport instead.
type SensitivitySettingsServerTransport struct {
	srv          *SensitivitySettingsServer
	newListPager *tracker[azfake.PagerResponder[armsecurity.SensitivitySettingsClientListResponse]]
}

// Do implements the policy.Transporter interface for SensitivitySettingsServerTransport.
func (s *SensitivitySettingsServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return s.dispatchToMethodFake(req, method)
}

func (s *SensitivitySettingsServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if sensitivitySettingsServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = sensitivitySettingsServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "SensitivitySettingsClient.CreateOrUpdate":
				res.resp, res.err = s.dispatchCreateOrUpdate(req)
			case "SensitivitySettingsClient.Get":
				res.resp, res.err = s.dispatchGet(req)
			case "SensitivitySettingsClient.NewListPager":
				res.resp, res.err = s.dispatchNewListPager(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (s *SensitivitySettingsServerTransport) dispatchCreateOrUpdate(req *http.Request) (*http.Response, error) {
	if s.srv.CreateOrUpdate == nil {
		return nil, &nonRetriableError{errors.New("fake for method CreateOrUpdate not implemented")}
	}
	body, err := server.UnmarshalRequestAsJSON[armsecurity.UpdateSensitivitySettingsRequest](req)
	if err != nil {
		return nil, err
	}
	respr, errRespr := s.srv.CreateOrUpdate(req.Context(), body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).GetSensitivitySettingsResponse, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SensitivitySettingsServerTransport) dispatchGet(req *http.Request) (*http.Response, error) {
	if s.srv.Get == nil {
		return nil, &nonRetriableError{errors.New("fake for method Get not implemented")}
	}
	respr, errRespr := s.srv.Get(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).GetSensitivitySettingsResponse, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SensitivitySettingsServerTransport) dispatchNewListPager(req *http.Request) (*http.Response, error) {
	if s.srv.NewListPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewListPager not implemented")}
	}
	newListPager := s.newListPager.get(req)
	if newListPager == nil {
		resp := s.srv.NewListPager(nil)
		newListPager = &resp
		s.newListPager.add(req, newListPager)
	}
	resp, err := server.PagerResponderNext(newListPager, req)
	if err != nil {
		return nil, err
	}
	if !slices.Contains([]int{http.StatusOK}, resp.StatusCode) {
		s.newListPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newListPager) {
		s.newListPager.remove(req)
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to SensitivitySettingsServerTransport
var sensitivitySettingsServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
