// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/policyinsights/armpolicyinsights"
	"net/http"
	"net/url"
	"regexp"
)

// PolicyStatesServer is a fake server for instances of the armpolicyinsights.PolicyStatesClient type.
type PolicyStatesServer struct {
	// BeginTriggerResourceGroupEvaluation is the fake for method PolicyStatesClient.BeginTriggerResourceGroupEvaluation
	// HTTP status codes to indicate success: http.StatusOK, http.StatusAccepted, http.StatusNoContent
	BeginTriggerResourceGroupEvaluation func(ctx context.Context, resourceGroupName string, options *armpolicyinsights.PolicyStatesClientBeginTriggerResourceGroupEvaluationOptions) (resp azfake.PollerResponder[armpolicyinsights.PolicyStatesClientTriggerResourceGroupEvaluationResponse], errResp azfake.ErrorResponder)

	// BeginTriggerSubscriptionEvaluation is the fake for method PolicyStatesClient.BeginTriggerSubscriptionEvaluation
	// HTTP status codes to indicate success: http.StatusOK, http.StatusAccepted, http.StatusNoContent
	BeginTriggerSubscriptionEvaluation func(ctx context.Context, options *armpolicyinsights.PolicyStatesClientBeginTriggerSubscriptionEvaluationOptions) (resp azfake.PollerResponder[armpolicyinsights.PolicyStatesClientTriggerSubscriptionEvaluationResponse], errResp azfake.ErrorResponder)
}

// NewPolicyStatesServerTransport creates a new instance of PolicyStatesServerTransport with the provided implementation.
// The returned PolicyStatesServerTransport instance is connected to an instance of armpolicyinsights.PolicyStatesClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewPolicyStatesServerTransport(srv *PolicyStatesServer) *PolicyStatesServerTransport {
	return &PolicyStatesServerTransport{
		srv:                                 srv,
		beginTriggerResourceGroupEvaluation: newTracker[azfake.PollerResponder[armpolicyinsights.PolicyStatesClientTriggerResourceGroupEvaluationResponse]](),
		beginTriggerSubscriptionEvaluation:  newTracker[azfake.PollerResponder[armpolicyinsights.PolicyStatesClientTriggerSubscriptionEvaluationResponse]](),
	}
}

// PolicyStatesServerTransport connects instances of armpolicyinsights.PolicyStatesClient to instances of PolicyStatesServer.
// Don't use this type directly, use NewPolicyStatesServerTransport instead.
type PolicyStatesServerTransport struct {
	srv                                 *PolicyStatesServer
	beginTriggerResourceGroupEvaluation *tracker[azfake.PollerResponder[armpolicyinsights.PolicyStatesClientTriggerResourceGroupEvaluationResponse]]
	beginTriggerSubscriptionEvaluation  *tracker[azfake.PollerResponder[armpolicyinsights.PolicyStatesClientTriggerSubscriptionEvaluationResponse]]
}

// Do implements the policy.Transporter interface for PolicyStatesServerTransport.
func (p *PolicyStatesServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return p.dispatchToMethodFake(req, method)
}

func (p *PolicyStatesServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result)
	defer close(resultChan)

	go func() {
		var intercepted bool
		var res result
		if policyStatesServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = policyStatesServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "PolicyStatesClient.BeginTriggerResourceGroupEvaluation":
				res.resp, res.err = p.dispatchBeginTriggerResourceGroupEvaluation(req)
			case "PolicyStatesClient.BeginTriggerSubscriptionEvaluation":
				res.resp, res.err = p.dispatchBeginTriggerSubscriptionEvaluation(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		select {
		case resultChan <- res:
		case <-req.Context().Done():
		}
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (p *PolicyStatesServerTransport) dispatchBeginTriggerResourceGroupEvaluation(req *http.Request) (*http.Response, error) {
	if p.srv.BeginTriggerResourceGroupEvaluation == nil {
		return nil, &nonRetriableError{errors.New("fake for method BeginTriggerResourceGroupEvaluation not implemented")}
	}
	beginTriggerResourceGroupEvaluation := p.beginTriggerResourceGroupEvaluation.get(req)
	if beginTriggerResourceGroupEvaluation == nil {
		const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/resourceGroups/(?P<resourceGroupName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.PolicyInsights/policyStates/latest/triggerEvaluation`
		regex := regexp.MustCompile(regexStr)
		matches := regex.FindStringSubmatch(req.URL.EscapedPath())
		if len(matches) < 3 {
			return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
		}
		resourceGroupNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("resourceGroupName")])
		if err != nil {
			return nil, err
		}
		respr, errRespr := p.srv.BeginTriggerResourceGroupEvaluation(req.Context(), resourceGroupNameParam, nil)
		if respErr := server.GetError(errRespr, req); respErr != nil {
			return nil, respErr
		}
		beginTriggerResourceGroupEvaluation = &respr
		p.beginTriggerResourceGroupEvaluation.add(req, beginTriggerResourceGroupEvaluation)
	}

	resp, err := server.PollerResponderNext(beginTriggerResourceGroupEvaluation, req)
	if err != nil {
		return nil, err
	}

	if !contains([]int{http.StatusOK, http.StatusAccepted, http.StatusNoContent}, resp.StatusCode) {
		p.beginTriggerResourceGroupEvaluation.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK, http.StatusAccepted, http.StatusNoContent", resp.StatusCode)}
	}
	if !server.PollerResponderMore(beginTriggerResourceGroupEvaluation) {
		p.beginTriggerResourceGroupEvaluation.remove(req)
	}

	return resp, nil
}

func (p *PolicyStatesServerTransport) dispatchBeginTriggerSubscriptionEvaluation(req *http.Request) (*http.Response, error) {
	if p.srv.BeginTriggerSubscriptionEvaluation == nil {
		return nil, &nonRetriableError{errors.New("fake for method BeginTriggerSubscriptionEvaluation not implemented")}
	}
	beginTriggerSubscriptionEvaluation := p.beginTriggerSubscriptionEvaluation.get(req)
	if beginTriggerSubscriptionEvaluation == nil {
		const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.PolicyInsights/policyStates/latest/triggerEvaluation`
		regex := regexp.MustCompile(regexStr)
		matches := regex.FindStringSubmatch(req.URL.EscapedPath())
		if len(matches) < 2 {
			return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
		}
		respr, errRespr := p.srv.BeginTriggerSubscriptionEvaluation(req.Context(), nil)
		if respErr := server.GetError(errRespr, req); respErr != nil {
			return nil, respErr
		}
		beginTriggerSubscriptionEvaluation = &respr
		p.beginTriggerSubscriptionEvaluation.add(req, beginTriggerSubscriptionEvaluation)
	}

	resp, err := server.PollerResponderNext(beginTriggerSubscriptionEvaluation, req)
	if err != nil {
		return nil, err
	}

	if !contains([]int{http.StatusOK, http.StatusAccepted, http.StatusNoContent}, resp.StatusCode) {
		p.beginTriggerSubscriptionEvaluation.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK, http.StatusAccepted, http.StatusNoContent", resp.StatusCode)}
	}
	if !server.PollerResponderMore(beginTriggerSubscriptionEvaluation) {
		p.beginTriggerSubscriptionEvaluation.remove(req)
	}

	return resp, nil
}

// set this to conditionally intercept incoming requests to PolicyStatesServerTransport
var policyStatesServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
