// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armhybridcompute_test

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/hybridcompute/armhybridcompute/v2"
	"log"
)

// Generated from example definition: 2025-09-16-preview/AgentVersion_GetLatest.json
func ExampleAgentVersionClient_Get() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armhybridcompute.NewClientFactory("<subscriptionID>", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewAgentVersionClient().Get(ctx, "myOsType", "1.27", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armhybridcompute.AgentVersionClientGetResponse{
	// 	AgentVersion: armhybridcompute.AgentVersion{
	// 		AgentVersion: to.Ptr("1.27"),
	// 		DownloadLink: to.Ptr("https://download.microsoft.com/download/8/4/5/845d5e04-bb09-4ed2-9ca8-bb51184cddc9/AzureConnectedMachineAgent.msi"),
	// 		OSType: to.Ptr("myOsType"),
	// 	},
	// }
}

// Generated from example definition: 2025-09-16-preview/AgentVersions_Get.json
func ExampleAgentVersionClient_NewListPager() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armhybridcompute.NewClientFactory("<subscriptionID>", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	pager := clientFactory.NewAgentVersionClient().NewListPager("myOsType", nil)
	for pager.More() {
		page, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range page.Value {
			// You could use page here. We use blank identifier for just demo purposes.
			_ = v
		}
		// If the HTTP response code is 200 as defined in example definition, your page structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
		// page = armhybridcompute.AgentVersionClientListResponse{
		// 	AgentVersionsList: armhybridcompute.AgentVersionsList{
		// 		Value: []*armhybridcompute.AgentVersion{
		// 			{
		// 				AgentVersion: to.Ptr("1.26"),
		// 				DownloadLink: to.Ptr("https://download.microsoft.com/download/8/4/5/845d5e04-bb09-4ed2-9ca8-bb51184cddc9/AzureConnectedMachineAgent.msi"),
		// 				OSType: to.Ptr("myOsType"),
		// 			},
		// 			{
		// 				AgentVersion: to.Ptr("1.27"),
		// 				DownloadLink: to.Ptr("https://download.microsoft.com/download/8/4/5/845d5e04-bb09-4ed2-9ca8-bb51184cddc9/AzureConnectedMachineAgent.msi"),
		// 				OSType: to.Ptr("myOsType"),
		// 			},
		// 		},
		// 	},
		// }
	}
}
