// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armhybridcompute

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// AgentVersionClient contains the methods for the AgentVersion group.
// Don't use this type directly, use NewAgentVersionClient() instead.
type AgentVersionClient struct {
	internal *arm.Client
}

// NewAgentVersionClient creates a new instance of AgentVersionClient with the specified values.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewAgentVersionClient(credential azcore.TokenCredential, options *arm.ClientOptions) (*AgentVersionClient, error) {
	cl, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	client := &AgentVersionClient{
		internal: cl,
	}
	return client, nil
}

// Get - Get a AgentVersion
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-09-16-preview
//   - osType - The id (Guid) of the Azure Arc PrivateLinkScope resource.
//   - version - The name of the agent version.
//   - options - AgentVersionClientGetOptions contains the optional parameters for the AgentVersionClient.Get method.
func (client *AgentVersionClient) Get(ctx context.Context, osType string, version string, options *AgentVersionClientGetOptions) (AgentVersionClientGetResponse, error) {
	var err error
	const operationName = "AgentVersionClient.Get"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCreateRequest(ctx, osType, version, options)
	if err != nil {
		return AgentVersionClientGetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return AgentVersionClientGetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return AgentVersionClientGetResponse{}, err
	}
	resp, err := client.getHandleResponse(httpResp)
	return resp, err
}

// getCreateRequest creates the Get request.
func (client *AgentVersionClient) getCreateRequest(ctx context.Context, osType string, version string, _ *AgentVersionClientGetOptions) (*policy.Request, error) {
	urlPath := "/providers/Microsoft.HybridCompute/osType/{osType}/agentVersions/{version}"
	if osType == "" {
		return nil, errors.New("parameter osType cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{osType}", url.PathEscape(osType))
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-09-16-preview")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// getHandleResponse handles the Get response.
func (client *AgentVersionClient) getHandleResponse(resp *http.Response) (AgentVersionClientGetResponse, error) {
	result := AgentVersionClientGetResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.AgentVersion); err != nil {
		return AgentVersionClientGetResponse{}, err
	}
	return result, nil
}

// NewListPager - Gets all agent versions based on location and publisher
//
// Generated from API version 2025-09-16-preview
//   - osType - The publisher of the agent version being received.
//   - options - AgentVersionClientListOptions contains the optional parameters for the AgentVersionClient.NewListPager method.
func (client *AgentVersionClient) NewListPager(osType string, options *AgentVersionClientListOptions) *runtime.Pager[AgentVersionClientListResponse] {
	return runtime.NewPager(runtime.PagingHandler[AgentVersionClientListResponse]{
		More: func(page AgentVersionClientListResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *AgentVersionClientListResponse) (AgentVersionClientListResponse, error) {
			ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "AgentVersionClient.NewListPager")
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listCreateRequest(ctx, osType, options)
			}, nil)
			if err != nil {
				return AgentVersionClientListResponse{}, err
			}
			return client.listHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listCreateRequest creates the List request.
func (client *AgentVersionClient) listCreateRequest(ctx context.Context, osType string, _ *AgentVersionClientListOptions) (*policy.Request, error) {
	urlPath := "/providers/Microsoft.HybridCompute/osType/{osType}/agentVersions"
	if osType == "" {
		return nil, errors.New("parameter osType cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{osType}", url.PathEscape(osType))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-09-16-preview")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// listHandleResponse handles the List response.
func (client *AgentVersionClient) listHandleResponse(resp *http.Response) (AgentVersionClientListResponse, error) {
	result := AgentVersionClientListResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.AgentVersionsList); err != nil {
		return AgentVersionClientListResponse{}, err
	}
	return result, nil
}
