// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armhybridcompute

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// ManagementClient - Azure Arc( Servers and K8s Clusters) API reference for Private Link's Scopes management.
// Don't use this type directly, use NewManagementClient() instead.
type ManagementClient struct {
	internal       *arm.Client
	subscriptionID string
}

// NewManagementClient creates a new instance of ManagementClient with the specified values.
//   - subscriptionID - The ID of the target subscription. The value must be an UUID.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewManagementClient(subscriptionID string, credential azcore.TokenCredential, options *arm.ClientOptions) (*ManagementClient, error) {
	cl, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	client := &ManagementClient{
		subscriptionID: subscriptionID,
		internal:       cl,
	}
	return client, nil
}

// NewAgentVersionClient creates a new instance of [AgentVersionClient].
func (client *ManagementClient) NewAgentVersionClient() *AgentVersionClient {
	return &AgentVersionClient{
		internal: client.internal,
	}
}

// NewExtensionMetadataClient creates a new instance of [ExtensionMetadataClient].
func (client *ManagementClient) NewExtensionMetadataClient() *ExtensionMetadataClient {
	return &ExtensionMetadataClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewExtensionMetadataV2Client creates a new instance of [ExtensionMetadataV2Client].
func (client *ManagementClient) NewExtensionMetadataV2Client() *ExtensionMetadataV2Client {
	return &ExtensionMetadataV2Client{
		internal: client.internal,
	}
}

// NewExtensionPublisherClient creates a new instance of [ExtensionPublisherClient].
func (client *ManagementClient) NewExtensionPublisherClient() *ExtensionPublisherClient {
	return &ExtensionPublisherClient{
		internal: client.internal,
	}
}

// NewExtensionTypeClient creates a new instance of [ExtensionTypeClient].
func (client *ManagementClient) NewExtensionTypeClient() *ExtensionTypeClient {
	return &ExtensionTypeClient{
		internal: client.internal,
	}
}

// NewGatewaysClient creates a new instance of [GatewaysClient].
func (client *ManagementClient) NewGatewaysClient() *GatewaysClient {
	return &GatewaysClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewHybridIdentityMetadataClient creates a new instance of [HybridIdentityMetadataClient].
func (client *ManagementClient) NewHybridIdentityMetadataClient() *HybridIdentityMetadataClient {
	return &HybridIdentityMetadataClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewLicenseProfilesClient creates a new instance of [LicenseProfilesClient].
func (client *ManagementClient) NewLicenseProfilesClient() *LicenseProfilesClient {
	return &LicenseProfilesClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewLicensesClient creates a new instance of [LicensesClient].
func (client *ManagementClient) NewLicensesClient() *LicensesClient {
	return &LicensesClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewMachineExtensionsClient creates a new instance of [MachineExtensionsClient].
func (client *ManagementClient) NewMachineExtensionsClient() *MachineExtensionsClient {
	return &MachineExtensionsClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewMachineRunCommandsClient creates a new instance of [MachineRunCommandsClient].
func (client *ManagementClient) NewMachineRunCommandsClient() *MachineRunCommandsClient {
	return &MachineRunCommandsClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewMachinesClient creates a new instance of [MachinesClient].
func (client *ManagementClient) NewMachinesClient() *MachinesClient {
	return &MachinesClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewNetworkConfigurationsClient creates a new instance of [NetworkConfigurationsClient].
func (client *ManagementClient) NewNetworkConfigurationsClient() *NetworkConfigurationsClient {
	return &NetworkConfigurationsClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewNetworkProfileClient creates a new instance of [NetworkProfileClient].
func (client *ManagementClient) NewNetworkProfileClient() *NetworkProfileClient {
	return &NetworkProfileClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewNetworkSecurityPerimeterConfigurationsClient creates a new instance of [NetworkSecurityPerimeterConfigurationsClient].
func (client *ManagementClient) NewNetworkSecurityPerimeterConfigurationsClient() *NetworkSecurityPerimeterConfigurationsClient {
	return &NetworkSecurityPerimeterConfigurationsClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewOperationsClient creates a new instance of [OperationsClient].
func (client *ManagementClient) NewOperationsClient() *OperationsClient {
	return &OperationsClient{
		internal: client.internal,
	}
}

// NewPrivateEndpointConnectionsClient creates a new instance of [PrivateEndpointConnectionsClient].
func (client *ManagementClient) NewPrivateEndpointConnectionsClient() *PrivateEndpointConnectionsClient {
	return &PrivateEndpointConnectionsClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewPrivateLinkResourcesClient creates a new instance of [PrivateLinkResourcesClient].
func (client *ManagementClient) NewPrivateLinkResourcesClient() *PrivateLinkResourcesClient {
	return &PrivateLinkResourcesClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewPrivateLinkScopesClient creates a new instance of [PrivateLinkScopesClient].
func (client *ManagementClient) NewPrivateLinkScopesClient() *PrivateLinkScopesClient {
	return &PrivateLinkScopesClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// NewSettingsClient creates a new instance of [SettingsClient].
func (client *ManagementClient) NewSettingsClient() *SettingsClient {
	return &SettingsClient{
		internal:       client.internal,
		subscriptionID: client.subscriptionID,
	}
}

// BeginSetupExtensions - The operation to Setup Machine Extensions.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-09-16-preview
//   - resourceGroupName - The name of the resource group. The name is case insensitive.
//   - machineName - The name of the hybrid machine.
//   - extensions - Parameters supplied to the Setup Extensions operation.
//   - options - ManagementClientBeginSetupExtensionsOptions contains the optional parameters for the ManagementClient.BeginSetupExtensions
//     method.
func (client *ManagementClient) BeginSetupExtensions(ctx context.Context, resourceGroupName string, machineName string, extensions SetupExtensionRequest, options *ManagementClientBeginSetupExtensionsOptions) (*runtime.Poller[ManagementClientSetupExtensionsResponse], error) {
	if options == nil || options.ResumeToken == "" {
		resp, err := client.setupExtensions(ctx, resourceGroupName, machineName, extensions, options)
		if err != nil {
			return nil, err
		}
		poller, err := runtime.NewPoller(resp, client.internal.Pipeline(), &runtime.NewPollerOptions[ManagementClientSetupExtensionsResponse]{
			Tracer: client.internal.Tracer(),
		})
		return poller, err
	} else {
		return runtime.NewPollerFromResumeToken(options.ResumeToken, client.internal.Pipeline(), &runtime.NewPollerFromResumeTokenOptions[ManagementClientSetupExtensionsResponse]{
			Tracer: client.internal.Tracer(),
		})
	}
}

// SetupExtensions - The operation to Setup Machine Extensions.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-09-16-preview
func (client *ManagementClient) setupExtensions(ctx context.Context, resourceGroupName string, machineName string, extensions SetupExtensionRequest, options *ManagementClientBeginSetupExtensionsOptions) (*http.Response, error) {
	var err error
	const operationName = "ManagementClient.BeginSetupExtensions"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.setupExtensionsCreateRequest(ctx, resourceGroupName, machineName, extensions, options)
	if err != nil {
		return nil, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK, http.StatusAccepted) {
		err = runtime.NewResponseError(httpResp)
		return nil, err
	}
	return httpResp, nil
}

// setupExtensionsCreateRequest creates the SetupExtensions request.
func (client *ManagementClient) setupExtensionsCreateRequest(ctx context.Context, resourceGroupName string, machineName string, extensions SetupExtensionRequest, _ *ManagementClientBeginSetupExtensionsOptions) (*policy.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HybridCompute/machines/{machineName}/addExtensions"
	if client.subscriptionID == "" {
		return nil, errors.New("parameter client.subscriptionID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	if resourceGroupName == "" {
		return nil, errors.New("parameter resourceGroupName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{resourceGroupName}", url.PathEscape(resourceGroupName))
	if machineName == "" {
		return nil, errors.New("parameter machineName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{machineName}", url.PathEscape(machineName))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-09-16-preview")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, extensions); err != nil {
		return nil, err
	}
	return req, nil
}

// BeginUpgradeExtensions - The operation to Upgrade Machine Extensions.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-09-16-preview
//   - resourceGroupName - The name of the resource group. The name is case insensitive.
//   - machineName - The name of the hybrid machine.
//   - extensionUpgradeParameters - Parameters supplied to the Upgrade Extensions operation.
//   - options - ManagementClientBeginUpgradeExtensionsOptions contains the optional parameters for the ManagementClient.BeginUpgradeExtensions
//     method.
func (client *ManagementClient) BeginUpgradeExtensions(ctx context.Context, resourceGroupName string, machineName string, extensionUpgradeParameters MachineExtensionUpgrade, options *ManagementClientBeginUpgradeExtensionsOptions) (*runtime.Poller[ManagementClientUpgradeExtensionsResponse], error) {
	if options == nil || options.ResumeToken == "" {
		resp, err := client.upgradeExtensions(ctx, resourceGroupName, machineName, extensionUpgradeParameters, options)
		if err != nil {
			return nil, err
		}
		poller, err := runtime.NewPoller(resp, client.internal.Pipeline(), &runtime.NewPollerOptions[ManagementClientUpgradeExtensionsResponse]{
			Tracer: client.internal.Tracer(),
		})
		return poller, err
	} else {
		return runtime.NewPollerFromResumeToken(options.ResumeToken, client.internal.Pipeline(), &runtime.NewPollerFromResumeTokenOptions[ManagementClientUpgradeExtensionsResponse]{
			Tracer: client.internal.Tracer(),
		})
	}
}

// UpgradeExtensions - The operation to Upgrade Machine Extensions.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-09-16-preview
func (client *ManagementClient) upgradeExtensions(ctx context.Context, resourceGroupName string, machineName string, extensionUpgradeParameters MachineExtensionUpgrade, options *ManagementClientBeginUpgradeExtensionsOptions) (*http.Response, error) {
	var err error
	const operationName = "ManagementClient.BeginUpgradeExtensions"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.upgradeExtensionsCreateRequest(ctx, resourceGroupName, machineName, extensionUpgradeParameters, options)
	if err != nil {
		return nil, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK, http.StatusAccepted) {
		err = runtime.NewResponseError(httpResp)
		return nil, err
	}
	return httpResp, nil
}

// upgradeExtensionsCreateRequest creates the UpgradeExtensions request.
func (client *ManagementClient) upgradeExtensionsCreateRequest(ctx context.Context, resourceGroupName string, machineName string, extensionUpgradeParameters MachineExtensionUpgrade, _ *ManagementClientBeginUpgradeExtensionsOptions) (*policy.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HybridCompute/machines/{machineName}/upgradeExtensions"
	if client.subscriptionID == "" {
		return nil, errors.New("parameter client.subscriptionID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	if resourceGroupName == "" {
		return nil, errors.New("parameter resourceGroupName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{resourceGroupName}", url.PathEscape(resourceGroupName))
	if machineName == "" {
		return nil, errors.New("parameter machineName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{machineName}", url.PathEscape(machineName))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-09-16-preview")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, extensionUpgradeParameters); err != nil {
		return nil, err
	}
	return req, nil
}
