// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armhybridcompute_test

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/hybridcompute/armhybridcompute/v2"
	"log"
)

// Generated from example definition: 2025-09-16-preview/networkConfiguration/NetworkConfigurationsCreate.json
func ExampleNetworkConfigurationsClient_CreateOrUpdate_networkConfigurationsCreate() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armhybridcompute.NewClientFactory("00000000-1111-2222-3333-444444444444", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewNetworkConfigurationsClient().CreateOrUpdate(ctx, "hybridRG", "testMachine", armhybridcompute.NetworkConfiguration{
		Properties: &armhybridcompute.NetworkConfigurationProperties{
			Location:                            to.Ptr("westus"),
			NetworkConfigurationScopeResourceID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/privateLinkScopes/testScope"),
		},
	}, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armhybridcompute.NetworkConfigurationsClientCreateOrUpdateResponse{
	// 	NetworkConfiguration: armhybridcompute.NetworkConfiguration{
	// 		ID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/machines/testMachine/providers/Microsoft.HybridCompute/networkConfigurations/current"),
	// 		Name: to.Ptr("current"),
	// 		Type: to.Ptr("Microsoft.HybridCompute/networkConfigurations"),
	// 		Properties: &armhybridcompute.NetworkConfigurationProperties{
	// 			Location: to.Ptr("westus"),
	// 			TenantID: to.Ptr("00000000-1111-2222-3333-444444444444"),
	// 			NetworkConfigurationScopeID: to.Ptr("00000000-1111-2222-3333-444444444444"),
	// 			NetworkConfigurationScopeResourceID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/privateLinkScopes/testScope"),
	// 			KeyProperties: &armhybridcompute.KeyProperties{
	// 				ClientPublicKey: &armhybridcompute.KeyDetails{
	// 					PublicKey: to.Ptr("62617365363420656e636f646564207075626c6963206b6579"),
	// 					NotAfter: to.Ptr(func() time.Time { t, _ := time.Parse(time.RFC3339Nano, "2021-01-01T00:00:00Z"); return t}()),
	// 					RenewAfter: to.Ptr(func() time.Time { t, _ := time.Parse(time.RFC3339Nano, "2021-02-01T00:00:00Z"); return t}()),
	// 				},
	// 			},
	// 		},
	// 	},
	// }
}

// Generated from example definition: 2025-09-16-preview/networkConfiguration/NetworkConfigurationsUpdate.json
func ExampleNetworkConfigurationsClient_CreateOrUpdate_networkConfigurationsUpdate() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armhybridcompute.NewClientFactory("00000000-1111-2222-3333-444444444444", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewNetworkConfigurationsClient().CreateOrUpdate(ctx, "hybridRG", "testMachine", armhybridcompute.NetworkConfiguration{
		Properties: &armhybridcompute.NetworkConfigurationProperties{
			NetworkConfigurationScopeResourceID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/privateLinkScopes/newScope"),
		},
	}, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armhybridcompute.NetworkConfigurationsClientCreateOrUpdateResponse{
	// 	NetworkConfiguration: armhybridcompute.NetworkConfiguration{
	// 		ID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/machines/testMachine/providers/Microsoft.HybridCompute/networkConfigurations/current"),
	// 		Name: to.Ptr("current"),
	// 		Type: to.Ptr("Microsoft.HybridCompute/networkConfigurations"),
	// 		Properties: &armhybridcompute.NetworkConfigurationProperties{
	// 			Location: to.Ptr("westus"),
	// 			TenantID: to.Ptr("00000000-1111-2222-3333-444444444444"),
	// 			NetworkConfigurationScopeID: to.Ptr("00000000-1111-2222-3333-444444444444"),
	// 			NetworkConfigurationScopeResourceID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/privateLinkScopes/newScope"),
	// 			KeyProperties: &armhybridcompute.KeyProperties{
	// 				ClientPublicKey: &armhybridcompute.KeyDetails{
	// 					PublicKey: to.Ptr("publickey"),
	// 					NotAfter: to.Ptr(func() time.Time { t, _ := time.Parse(time.RFC3339Nano, "2021-01-01T00:00:00Z"); return t}()),
	// 					RenewAfter: to.Ptr(func() time.Time { t, _ := time.Parse(time.RFC3339Nano, "2021-02-01T00:00:00Z"); return t}()),
	// 				},
	// 			},
	// 		},
	// 	},
	// }
}

// Generated from example definition: 2025-09-16-preview/networkConfiguration/NetworkConfigurationsGet.json
func ExampleNetworkConfigurationsClient_Get() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armhybridcompute.NewClientFactory("00000000-1111-2222-3333-444444444444", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewNetworkConfigurationsClient().Get(ctx, "hybridRG", "testMachine", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armhybridcompute.NetworkConfigurationsClientGetResponse{
	// 	NetworkConfiguration: armhybridcompute.NetworkConfiguration{
	// 		ID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/machines/testMachine/providers/Microsoft.HybridCompute/networkConfigurations/current"),
	// 		Name: to.Ptr("current"),
	// 		Type: to.Ptr("Microsoft.HybridCompute/networkConfigurations"),
	// 		Properties: &armhybridcompute.NetworkConfigurationProperties{
	// 			TenantID: to.Ptr("default"),
	// 			Location: to.Ptr("westus"),
	// 			NetworkConfigurationScopeID: to.Ptr("00000000-1111-2222-3333-444444444444"),
	// 			NetworkConfigurationScopeResourceID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/privateLinkScopes/testScope"),
	// 			KeyProperties: &armhybridcompute.KeyProperties{
	// 				ClientPublicKey: &armhybridcompute.KeyDetails{
	// 					PublicKey: to.Ptr("62617365363420656e636f646564207075626c6963206b6579"),
	// 					NotAfter: to.Ptr(func() time.Time { t, _ := time.Parse(time.RFC3339Nano, "2021-01-01T00:00:00Z"); return t}()),
	// 					RenewAfter: to.Ptr(func() time.Time { t, _ := time.Parse(time.RFC3339Nano, "2021-02-01T00:00:00Z"); return t}()),
	// 				},
	// 			},
	// 		},
	// 	},
	// }
}

// Generated from example definition: 2025-09-16-preview/networkConfiguration/NetworkConfigurationsPatch.json
func ExampleNetworkConfigurationsClient_Update() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armhybridcompute.NewClientFactory("00000000-1111-2222-3333-444444444444", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewNetworkConfigurationsClient().Update(ctx, "hybridRG", "testMachine", armhybridcompute.NetworkConfiguration{
		Properties: &armhybridcompute.NetworkConfigurationProperties{
			NetworkConfigurationScopeResourceID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/privateLinkScopes/newScope"),
		},
	}, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armhybridcompute.NetworkConfigurationsClientUpdateResponse{
	// 	NetworkConfiguration: armhybridcompute.NetworkConfiguration{
	// 		ID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/machines/testMachine/providers/Microsoft.HybridCompute/networkConfigurations/current"),
	// 		Name: to.Ptr("current"),
	// 		Type: to.Ptr("Microsoft.HybridCompute/networkConfigurations"),
	// 		Properties: &armhybridcompute.NetworkConfigurationProperties{
	// 			Location: to.Ptr("westus"),
	// 			TenantID: to.Ptr("00000000-1111-2222-3333-444444444444"),
	// 			NetworkConfigurationScopeID: to.Ptr("00000000-1111-2222-3333-444444444444"),
	// 			NetworkConfigurationScopeResourceID: to.Ptr("/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/hybridRG/providers/Microsoft.HybridCompute/privateLinkScopes/newScope"),
	// 			KeyProperties: &armhybridcompute.KeyProperties{
	// 				ClientPublicKey: &armhybridcompute.KeyDetails{
	// 					PublicKey: to.Ptr("publickey"),
	// 					NotAfter: to.Ptr(func() time.Time { t, _ := time.Parse(time.RFC3339Nano, "2021-01-01T00:00:00Z"); return t}()),
	// 					RenewAfter: to.Ptr(func() time.Time { t, _ := time.Parse(time.RFC3339Nano, "2021-02-01T00:00:00Z"); return t}()),
	// 				},
	// 			},
	// 		},
	// 	},
	// }
}
